SET SCHEMA INTUIT;

INSERT INTO INS_MOD (MOD_CODE, MOD_NAME, MOD_IUSE) VALUES ('CS118-15', 'Programming for Computer Scientists', 'Y');

INSERT INTO CAM_AST (AST_CODE, AST_NAME, AST_IUSE) VALUES ('ES', 'Examination - Summer', 'Y');
INSERT INTO CAM_AST (AST_CODE, AST_NAME, AST_IUSE) VALUES ('WRI', 'Essay', 'Y');
INSERT INTO CAM_AST (AST_CODE, AST_NAME, AST_IUSE) VALUES ('O', 'Other', 'Y');
INSERT INTO CAM_AST (AST_CODE, AST_NAME, AST_IUSE) VALUES ('DA', 'Design Assignment', 'Y');
INSERT INTO CAM_AST (AST_CODE, AST_NAME, AST_IUSE) VALUES ('T', 'In-Class Test', 'Y');
INSERT INTO CAM_AST (AST_CODE, AST_NAME, AST_IUSE) VALUES ('D', 'Dissertation', 'Y');

INSERT INTO SRS_FAC (FAC_CODE, FAC_NAME, FAC_IUSE) VALUES ('A', 'Arts', 'Y');
INSERT INTO SRS_FAC (FAC_CODE, FAC_NAME, FAC_IUSE) VALUES ('S', 'Science', 'Y');
INSERT INTO SRS_FAC (FAC_CODE, FAC_NAME, FAC_IUSE) VALUES ('T', 'Social Sciences', 'Y');
INSERT INTO SRS_FAC (FAC_CODE, FAC_NAME, FAC_IUSE) VALUES ('X', 'No Faculty', 'Y');
INSERT INTO SRS_FAC (FAC_CODE, FAC_NAME, FAC_IUSE) VALUES ('M', 'Medicine', 'Y');
INSERT INTO SRS_FAC (FAC_CODE, FAC_NAME, FAC_IUSE) VALUES ('I', 'Interdisciplinary/Cross-Faculty', 'Y');

INSERT INTO INS_DPT (DPT_CODE, DPT_NAME, DPT_TYPE, DPT_IUSE, DPT_FACC) VALUES ('CS', 'Computer Science', 'DEP', 'Y', 'S');
INSERT INTO INS_DPT (DPT_CODE, DPT_NAME, DPT_TYPE, DPT_IUSE, DPT_FACC) VALUES ('MA', 'Mathematics Institute', 'DEP', 'Y', 'S');
INSERT INTO INS_DPT (DPT_CODE, DPT_NAME, DPT_TYPE, DPT_IUSE, DPT_FACC) VALUES ('ES', 'School of Engineering', 'SCH', 'Y', 'S');
INSERT INTO INS_DPT (DPT_CODE, DPT_NAME, DPT_TYPE, DPT_IUSE, DPT_FACC) VALUES ('LN', 'School of Modern Languages and Cultures', 'DEP', 'Y', 'A');
INSERT INTO INS_DPT (DPT_CODE, DPT_NAME, DPT_TYPE, DPT_IUSE, DPT_FACC) VALUES ('EC', 'Economics', 'DEP', 'Y', 'T');
INSERT INTO INS_DPT (DPT_CODE, DPT_NAME, DPT_TYPE, DPT_IUSE, DPT_FACC) VALUES ('IN', 'IT Services', 'ADM', 'Y', 'X');

INSERT INTO CAM_LEV (LEV_CODE, LEV_NAME, LEV_IUSE) VALUES ('1', 'Undergraduate Level 1', 'Y');
INSERT INTO CAM_LEV (LEV_CODE, LEV_NAME, LEV_IUSE) VALUES ('2', 'Undergraduate Level 2', 'Y');
INSERT INTO CAM_LEV (LEV_CODE, LEV_NAME, LEV_IUSE) VALUES ('3', 'Undergraduate Level 3', 'Y');
INSERT INTO CAM_LEV (LEV_CODE, LEV_NAME, LEV_IUSE) VALUES ('4', 'Undergraduate Level 4', 'Y');
INSERT INTO CAM_LEV (LEV_CODE, LEV_NAME, LEV_IUSE) VALUES ('5', 'Undergraduate Level 5', 'Y');
INSERT INTO CAM_LEV (LEV_CODE, LEV_NAME, LEV_IUSE) VALUES ('6', 'Undergraduate Level 6', 'Y');
INSERT INTO CAM_LEV (LEV_CODE, LEV_NAME, LEV_IUSE) VALUES ('7', 'Undergraduate Level 7', 'Y');
INSERT INTO CAM_LEV (LEV_CODE, LEV_NAME, LEV_IUSE) VALUES ('8', 'Undergraduate Level 8', 'Y');
INSERT INTO CAM_LEV (LEV_CODE, LEV_NAME, LEV_IUSE) VALUES ('9', 'Undergraduate Level 9', 'Y');
INSERT INTO CAM_LEV (LEV_CODE, LEV_NAME, LEV_IUSE) VALUES ('10', 'Undergraduate Level 10', 'Y');
INSERT INTO CAM_LEV (LEV_CODE, LEV_NAME, LEV_IUSE) VALUES ('11', 'Undergraduate Level 11', 'Y');
INSERT INTO CAM_LEV (LEV_CODE, LEV_NAME, LEV_IUSE) VALUES ('12', 'Undergraduate Level 12', 'Y');
INSERT INTO CAM_LEV (LEV_CODE, LEV_NAME, LEV_IUSE) VALUES ('F', 'Foundation', 'Y');
INSERT INTO CAM_LEV (LEV_CODE, LEV_NAME, LEV_IUSE) VALUES ('M1', 'Taught Postgraduate Level', 'Y');
INSERT INTO CAM_LEV (LEV_CODE, LEV_NAME, LEV_IUSE) VALUES ('M2', 'Research Postgraduate Level', 'Y');
INSERT INTO CAM_LEV (LEV_CODE, LEV_NAME, LEV_IUSE) VALUES ('X', 'Post-Experience', 'Y');