DROP SCHEMA IF EXISTS INTUIT CASCADE;
CREATE SCHEMA INTUIT;
SET SCHEMA INTUIT;

CREATE TABLE INS_MOD
(
    MOD_CODE  NVARCHAR2(12) not null
        constraint INS_MODP1
            primary key,
    DOM_CODE  NVARCHAR2(12),
    MOD_SNAM  NVARCHAR2(15),
    MOD_NAME  NVARCHAR2(120),
    SCH_CODE  NVARCHAR2(6),
    LEV_CODE  NVARCHAR2(6),
    PRS_CODE  NVARCHAR2(12),
    MOT_CODE  NVARCHAR2(6),
    MOD_CRDT  NUMBER(5, 2),
    MOD_HOURS NUMBER(4),
    MAP_CODE  NVARCHAR2(12),
    MOD_EREF  NVARCHAR2(12),
    MKS_CODE  NVARCHAR2(6),
    FPT_CODE  NVARCHAR2(12),
    ESB_CODE  NVARCHAR2(6),
    MOD_NPER  NUMBER(2),
    MOD_MOAS  NVARCHAR2(1),
    MOD_PMOA  NVARCHAR2(1),
    MEP_CODE  NVARCHAR2(6),
    DPT_CODE  NVARCHAR2(12),
    ELV_CODE  NVARCHAR2(3),
    ECL_CODE  NVARCHAR2(3),
    MOD_UTYC  NVARCHAR2(3),
    MOD_COGC  NVARCHAR2(6),
    MOD_STAT  VARCHAR2(1),
    MOD_UPDD  DATE,
    MOD_KEYW  NVARCHAR2(100),
    MOD_IUSE  VARCHAR2(1),
    MOD_TOCC  NVARCHAR2(12),
    MOD_DVNC  NVARCHAR2(12),
    MOD_UDF1  NVARCHAR2(15),
    MOD_UDF2  NVARCHAR2(15),
    MOD_UDF3  NVARCHAR2(15),
    MOD_UDF4  NVARCHAR2(15),
    MOD_UDF5  NVARCHAR2(15),
    MOD_UDF6  NVARCHAR2(15),
    MOD_UDF7  NVARCHAR2(15),
    MOD_UDF8  NVARCHAR2(15),
    MOD_UDF9  NVARCHAR2(15),
    MOD_UDFA  NVARCHAR2(15),
    MOD_UDFB  NVARCHAR2(15),
    MOD_UDFC  NVARCHAR2(15),
    MOD_UDFD  NVARCHAR2(15),
    MOD_UDFE  NVARCHAR2(15),
    MOD_UDFF  NVARCHAR2(15),
    MOD_UDFG  NVARCHAR2(15),
    MOD_UDFH  NVARCHAR2(15),
    MOD_UDFI  NVARCHAR2(15),
    MOD_UDFJ  NVARCHAR2(100),
    MOD_UDFK  NVARCHAR2(100),
    MOD_VALC  NVARCHAR2(12),
    MOD_APRT  NUMBER(5, 2),
    MOD_LANG  NVARCHAR2(1),
    MOD_ERFM  NVARCHAR2(1),
    MOD_MUSE  VARCHAR2(1),
    MOD_FACC  NVARCHAR2(6),
    MOD_ISGX  VARCHAR2(1),
    MOD_REGM  NVARCHAR2(1),
    MOD_FRID  VARCHAR2(1),
    MOD_WEEI  NVARCHAR2(1),
    MOD_MODE  NVARCHAR2(1),
    MOD_ARPT  VARCHAR2(1),
    MOD_NOTE  NCLOB
);

create table INTUIT.CAM_MAB
(
    MAP_CODE  NVARCHAR2(12) not null,
    MAB_SEQ   NVARCHAR2(3)  not null,
    AST_CODE  NVARCHAR2(6),
    MAB_PERC  NUMBER(4),
    MAB_TSHA  NUMBER(5),
    MAB_NAME  NVARCHAR2(120),
    MAB_DDAY  NUMBER(1),
    MAB_DWEEK NUMBER(2),
    MAB_DPRD  NUMBER(2),
    MAB_HOURS NUMBER(5, 2),
    MKS_CODE  NVARCHAR2(6),
    MAB_QMARK NUMBER(7),
    MAB_QSET  NVARCHAR2(2),
    MAB_AGRP  NVARCHAR2(2),
    MAB_RGRP  NVARCHAR2(2),
    MAB_RASI  NVARCHAR2(2),
    MAB_APAC  NVARCHAR2(12),
    MAB_ADVC  NVARCHAR2(12),
    MAB_BRIC  NVARCHAR2(16),
    MAB_EXBD  DATE,
    MAB_EREF  NVARCHAR2(12),
    MAB_HMRK  NVARCHAR2(1),
    MAB_USCD  NVARCHAR2(1),
    MAB_MCDF  NVARCHAR2(1),
    MAB_GGFM  NVARCHAR2(1),
    MAB_DUAW  VARCHAR2(1),
    MAB_PNAM  NVARCHAR2(1),
    MAB_STAD  NVARCHAR2(1),
    MAB_SORT  NVARCHAR2(30),
    MAB_NUSE  VARCHAR2(1),
    MAB_ELOG  VARCHAR2(1),
    MAB_DURM  VARCHAR2(1),
    MAB_UDF1  NVARCHAR2(15),
    MAB_UDF2  NVARCHAR2(15),
    MAB_UDF3  NVARCHAR2(15),
    MAB_UDF4  NVARCHAR2(15),
    MAB_UDF5  NVARCHAR2(15),
    MAB_UDF6  NVARCHAR2(15),
    MAB_UDF7  NVARCHAR2(15),
    MAB_UDF8  NVARCHAR2(15),
    MAB_UDF9  NVARCHAR2(15),
    MAB_UDFA  NVARCHAR2(15),
    MAB_UDFB  NVARCHAR2(15),
    MAB_UDFC  NVARCHAR2(15),
    MAB_UDFD  NVARCHAR2(15),
    MAB_UDFE  NVARCHAR2(15),
    MAB_UDFF  NVARCHAR2(15),
    MAB_UDFG  NVARCHAR2(15),
    MAB_UDFH  NVARCHAR2(15),
    MAB_UDFI  NVARCHAR2(15),
    MAB_UDFJ  NVARCHAR2(100),
    MAB_UDFK  NVARCHAR2(100),
    MAB_LOCK  VARCHAR2(1),
    MAB_IUSE  VARCHAR2(1),
    MAB_AQHC  NVARCHAR2(16),
    MAB_AQH1  NVARCHAR2(16),
    MAB_CGRP  NVARCHAR2(6),
    MAB_FAYN  VARCHAR2(1),
    MAB_GMTH  NVARCHAR2(1),
    MAB_GSTU  NUMBER(3),
    MAB_GINI  NUMBER(2),
    MAB_GMAX  NUMBER(2),
    MAB_DUET  DATE,
    MAB_IRQP  VARCHAR2(1),
    MAB_DTYC  NVARCHAR2(32),
    MAB_FBOC  NVARCHAR2(12),
    MAB_TIIC  NVARCHAR2(16),
    MAB_PRCC  NVARCHAR2(12),
    MAB_ASID  NVARCHAR2(12),
    MAB_HOHM  DATE,
    MAB_DOUB  VARCHAR2(1),
    constraint CAM_MABP1
        primary key (MAP_CODE, MAB_SEQ)
);

create index INTUIT.CAM_MABI2
    on INTUIT.CAM_MAB (AST_CODE);

create index INTUIT.CAM_MABI3
    on INTUIT.CAM_MAB (MKS_CODE);

create index INTUIT.CAM_MABI4
    on INTUIT.CAM_MAB (MAP_CODE);

create index INTUIT.CAM_MABI5
    on INTUIT.CAM_MAB (MAB_EREF);

create index INTUIT.CAM_MABI6
    on INTUIT.CAM_MAB (MAB_APAC);

create index INTUIT.CAM_MABI7
    on INTUIT.CAM_MAB (MAB_APAC, MAB_ADVC);

create index INTUIT.CAM_MABI8
    on INTUIT.CAM_MAB (MAB_ASID);


create table INTUIT.CAM_APA
(
    APA_CODE NVARCHAR2(12) not null
        constraint CAM_APAP1
            primary key,
    APA_SNAM NVARCHAR2(15),
    APA_NAME NVARCHAR2(50),
    APA_PRSC NVARCHAR2(12),
    APA_APSC NVARCHAR2(6)  not null,
    APA_APTC NVARCHAR2(6)  not null,
    APA_ROMC NVARCHAR2(15),
    APA_NOTE NVARCHAR2(2000),
    APA_SEAT NUMBER(2),
    APA_MSCC NVARCHAR2(12),
    APA_WJRC NVARCHAR2(12),
    APA_MSCP VARCHAR2(1),
    APA_WJRP VARCHAR2(1),
    APA_SGVN VARCHAR2(1),
    APA_APDC NVARCHAR2(12),
    APA_PWGT NUMBER(5, 2)
);

create index INTUIT.CAM_APAI2
    on INTUIT.CAM_APA (APA_PRSC);

create index INTUIT.CAM_APAI3
    on INTUIT.CAM_APA (APA_APSC);

create index INTUIT.CAM_APAI4
    on INTUIT.CAM_APA (APA_ROMC);

create table INTUIT.CAM_ADV
(
    ADV_APAC NVARCHAR2(12) not null,
    ADV_CODE NVARCHAR2(12) not null,
    ADV_SNAM NVARCHAR2(15),
    ADV_DURA DATE,
    ADV_RDTM DATE,
    ADV_NUMQ NUMBER(2),
    ADV_MAXQ NUMBER(2),
    ADV_MINQ NUMBER(2),
    ADV_MFEE NUMBER(15, 2),
    ADV_NOTE NVARCHAR2(2000),
    constraint CAM_ADVP1
        primary key (ADV_APAC, ADV_CODE)
);

create index INTUIT.CAM_ADVI2
    on INTUIT.CAM_ADV (ADV_APAC);

create table INTUIT.CAM_ADR
(
    ADR_APAC NVARCHAR2(12) not null,
    ADR_ADVC NVARCHAR2(12) not null,
    ADR_SEQN NVARCHAR2(3)  not null,
    ADR_ARQC NVARCHAR2(6)  not null,
    ADR_NUMO NUMBER(20)    not null,
    constraint CAM_ADRP1
        primary key (ADR_APAC, ADR_ADVC, ADR_SEQN)
);

create index INTUIT.CAM_ADRI2
    on INTUIT.CAM_ADR (ADR_APAC, ADR_ADVC);

create index INTUIT.CAM_ADRI3
    on INTUIT.CAM_ADR (ADR_APAC);

create index INTUIT.CAM_ADRI4
    on INTUIT.CAM_ADR (ADR_ARQC);

create table INTUIT.CAM_ARQ
(
    ARQ_CODE NVARCHAR2(6) not null
        constraint CAM_ARQP1
            primary key,
    ARQ_SNAM NVARCHAR2(15),
    ARQ_NAME NVARCHAR2(255),
    ARQ_ARTC NVARCHAR2(6) not null
);

create index INTUIT.CAM_ARQI2
    on INTUIT.CAM_ARQ (ARQ_ARTC);
create table INTUIT.CAM_MAP
(
    MAP_CODE  NVARCHAR2(12) not null
        constraint CAM_MAPP1
            primary key,
    MAP_SNAM  NVARCHAR2(15),
    MAP_NAME  NVARCHAR2(50),
    MKS2_CODE NVARCHAR2(6),
    MKS3_CODE NVARCHAR2(6),
    MAP_HIGM  NVARCHAR2(1),
    MAP_AGRP  NVARCHAR2(2),
    MAP_PNAME NVARCHAR2(1),
    MAP_MMSC  NVARCHAR2(6),
    MAP_USCD  NVARCHAR2(1),
    MAP_MCDF  NVARCHAR2(1),
    MAP_GGFM  NVARCHAR2(1),
    MAP_TMRF  CHAR,
    MAP_REAL  CHAR,
    MAP_C100  CHAR,
    MAP_MXRI  NUMBER(1),
    MAP_AWRI  VARCHAR2(1),
    MAP_MWRI  VARCHAR2(1),
    MAP_WMODE NVARCHAR2(1),
    MAP_SCDF  NVARCHAR2(1),
    MAP_SORT  NVARCHAR2(30),
    MAP_ARIS  VARCHAR2(1),
    MAP_TACT  NVARCHAR2(6),
    MAP_PMRK  NVARCHAR2(6),
    MAP_IUSE  VARCHAR2(1),
    MAP_LOCK  VARCHAR2(1),
    MAP_UMRK  VARCHAR2(1),
    MAP_MHCC  NVARCHAR2(16),
    MAP_RASM  VARCHAR2(1),
    MAP_USDR  VARCHAR2(1),
    MAP_AEGR  VARCHAR2(1),
    MAP_UDF1  NVARCHAR2(15),
    MAP_UDF2  NVARCHAR2(15),
    MAP_UDF3  NVARCHAR2(15),
    MAP_UDF4  NVARCHAR2(15),
    MAP_UDF5  NVARCHAR2(15),
    MAP_UDF6  NVARCHAR2(15),
    MAP_UDF7  NVARCHAR2(15),
    MAP_UDF8  NVARCHAR2(15),
    MAP_UDF9  NVARCHAR2(15),
    MAP_UDFA  NVARCHAR2(15),
    MAP_UDFB  NVARCHAR2(15),
    MAP_UDFC  NVARCHAR2(15),
    MAP_UDFD  NVARCHAR2(15),
    MAP_UDFE  NVARCHAR2(15),
    MAP_UDFF  NVARCHAR2(15),
    MAP_UDFG  NVARCHAR2(15),
    MAP_UDFH  NVARCHAR2(15),
    MAP_UDFI  NVARCHAR2(15),
    MAP_UDFJ  NVARCHAR2(100),
    MAP_UDFK  NVARCHAR2(100),
    MAP_DAQE  NVARCHAR2(1)
);

create index INTUIT.CAM_MAPI2
    on INTUIT.CAM_MAP (MKS2_CODE);

create index INTUIT.CAM_MAPI3
    on INTUIT.CAM_MAP (MKS3_CODE);

create table INTUIT.CAM_AST
(
    AST_CODE  NVARCHAR2(6) not null
        constraint CAM_ASTP1
            primary key,
    AST_SNAM  NVARCHAR2(15),
    AST_NAME  NVARCHAR2(50),
    AST_GENDD NVARCHAR2(1),
    AST_PNAME NVARCHAR2(1),
    AST_RECLD NVARCHAR2(1),
    AST_PNAM  NVARCHAR2(1),
    AST_MKSC  NVARCHAR2(6),
    AST_USCD  NVARCHAR2(1),
    AST_MCDF  NVARCHAR2(1),
    AST_GGFM  NVARCHAR2(1),
    AST_STAD  NVARCHAR2(1),
    AST_SORT  NVARCHAR2(30),
    AST_EXDY  NUMBER(2),
    AST_IUSE  VARCHAR2(1),
    AST_UDF1  NVARCHAR2(15),
    AST_UDF2  NVARCHAR2(15),
    AST_UDF3  NVARCHAR2(15),
    AST_UDF4  NVARCHAR2(15),
    AST_UDF5  NVARCHAR2(15),
    AST_UDF6  NVARCHAR2(15),
    AST_UDF7  NVARCHAR2(15),
    AST_UDF8  NVARCHAR2(15),
    AST_UDF9  NVARCHAR2(15),
    AST_UDFA  NVARCHAR2(15),
    AST_UDFB  NVARCHAR2(15),
    AST_UDFC  NVARCHAR2(15),
    AST_UDFD  NVARCHAR2(15),
    AST_UDFE  NVARCHAR2(15),
    AST_UDFF  NVARCHAR2(15),
    AST_UDFG  NVARCHAR2(15),
    AST_UDFH  NVARCHAR2(15),
    AST_UDFI  NVARCHAR2(15),
    AST_UDFJ  NVARCHAR2(100),
    AST_UDFK  NVARCHAR2(100)
);


create table INTUIT.SRS_CRS
(
    CRS_CODE   NVARCHAR2(15) not null
        constraint SRS_CRSP1
            primary key,
    CRS_SNAM   NVARCHAR2(15),
    CRS_NAME   NVARCHAR2(50),
    CRS_TITL   NVARCHAR2(120),
    CRS_CGPC   NVARCHAR2(12),
    CRS_DPTC   NVARCHAR2(12),
    CRS_PRSC   NVARCHAR2(12),
    CRS_SCHC   NVARCHAR2(6),
    CRS_COSC   NVARCHAR2(6),
    CRS_TOPC   NVARCHAR2(3),
    CRS_MOEN   NVARCHAR2(2),
    CRS_BEGD   DATE,
    CRS_ENDD   DATE,
    CRS_YLEN   NUMBER(2),
    CRS_FPTC   NVARCHAR2(12),
    CRS_MOAC   NVARCHAR2(6),
    CRS_QULC   NVARCHAR2(3),
    CRS_ESB1   NVARCHAR2(6),
    CRS_EIN1   NVARCHAR2(1),
    CRS_ESB2   NVARCHAR2(6),
    CRS_EIN2   NVARCHAR2(1),
    CRS_ESB3   NVARCHAR2(6),
    CRS_EBAL   NVARCHAR2(1),
    CRS_CTYC   NVARCHAR2(3),
    CRS_LENG   NUMBER(2),
    CRS_UOMC   NVARCHAR2(6),
    CRS_STTC   NVARCHAR2(6),
    CRS_ERFM   NVARCHAR2(1),
    CRS_XRFM   NVARCHAR2(2),
    CRS_FECM   NVARCHAR2(1),
    CRS_TTIC   NVARCHAR2(3),
    CRS_CSF1   NVARCHAR2(3),
    CRS_CSF2   NVARCHAR2(3),
    CRS_SDPTC  NVARCHAR2(12),
    CRS_CRSSTC NVARCHAR2(15),
    CRS_HEFE   NVARCHAR2(1),
    CRS_URLR   NVARCHAR2(50),
    CRS_FACC   NVARCHAR2(6),
    CRS_GSAF   VARCHAR2(1),
    CRS_GSCF   VARCHAR2(1),
    CRS_PSAC   NVARCHAR2(12),
    CRS_GAEL   NVARCHAR2(1),
    CRS_CLSC   NVARCHAR2(1),
    CRS_RESH   VARCHAR2(1),
    CRS_IUSE   VARCHAR2(1),
    CRS_FRFM   NVARCHAR2(1),
    CRS_SRFM   NVARCHAR2(1),
    CRS_ELQS   VARCHAR2(1),
    CRS_BURS   VARCHAR2(1),
    CRS_SKEO   VARCHAR2(1),
    CRS_UDF1   NVARCHAR2(15),
    CRS_UDF2   NVARCHAR2(15),
    CRS_UDF3   NVARCHAR2(15),
    CRS_UDF4   NVARCHAR2(15),
    CRS_UDF5   NVARCHAR2(15),
    CRS_UDF6   NVARCHAR2(15),
    CRS_UDF7   NVARCHAR2(15),
    CRS_UDF8   NVARCHAR2(15),
    CRS_UDF9   NVARCHAR2(15),
    CRS_UDFA   NVARCHAR2(15),
    CRS_UDFB   NVARCHAR2(15),
    CRS_UDFC   NVARCHAR2(15),
    CRS_UDFD   NVARCHAR2(15),
    CRS_UDFE   NVARCHAR2(15),
    CRS_UDFF   NVARCHAR2(15),
    CRS_UDFG   NVARCHAR2(15),
    CRS_UDFH   NVARCHAR2(15),
    CRS_UDFI   NVARCHAR2(15),
    CRS_UDFJ   NVARCHAR2(100),
    CRS_UDFK   NVARCHAR2(100),
    CRS_NOTE   NVARCHAR2(2000),
    CRS_MDOS   NUMBER(2),
    CRS_DVNC   NVARCHAR2(12),
    CRS_TAIC   NVARCHAR2(6),
    CRS_ENRC   NVARCHAR2(6),
    CRS_HASC   NVARCHAR2(12),
    CRS_ESB4   NVARCHAR2(6),
    CRS_ESB5   NVARCHAR2(6)
);

create index INTUIT.SRS_CRSI2
    on INTUIT.SRS_CRS (CRS_DPTC);

create index INTUIT.SRS_CRSI3
    on INTUIT.SRS_CRS (CRS_PRSC);

create index INTUIT.SRS_CRSI4
    on INTUIT.SRS_CRS (CRS_SCHC);

create index INTUIT.SRS_CRSI5
    on INTUIT.SRS_CRS (CRS_BEGD);

create index INTUIT.SRS_CRSI6
    on INTUIT.SRS_CRS (CRS_ENDD);

create index INTUIT.SRS_CRSI7
    on INTUIT.SRS_CRS (CRS_FPTC);

create index INTUIT.SRS_CRSI8
    on INTUIT.SRS_CRS (CRS_MOAC);

create index INTUIT.SRS_CRSI9
    on INTUIT.SRS_CRS (CRS_QULC);

create index INTUIT.SRS_CRSI10
    on INTUIT.SRS_CRS (CRS_ESB1);

create index INTUIT.SRS_CRSI11
    on INTUIT.SRS_CRS (CRS_ESB2);

create index INTUIT.SRS_CRSI12
    on INTUIT.SRS_CRS (CRS_CTYC);

create index INTUIT.SRS_CRSI13
    on INTUIT.SRS_CRS (CRS_UOMC);

create index INTUIT.SRS_CRSI14
    on INTUIT.SRS_CRS (CRS_STTC);

create index INTUIT.SRS_CRSI15
    on INTUIT.SRS_CRS (CRS_TTIC);

create index INTUIT.SRS_CRSI16
    on INTUIT.SRS_CRS (CRS_CSF1);

create index INTUIT.SRS_CRSI17
    on INTUIT.SRS_CRS (CRS_CSF2);

create index INTUIT.SRS_CRSI18
    on INTUIT.SRS_CRS (CRS_CGPC);

create table INTUIT.INS_DPT
(
    DPT_CODE NVARCHAR2(12) not null
        constraint INS_DPTP1
            primary key,
    DPT_SNAM NVARCHAR2(15),
    DPT_NAME NVARCHAR2(250),
    DPT_INSC NVARCHAR2(6),
    DPT_IUSE VARCHAR2(1),
    DPT_TYPE NVARCHAR2(12),
    DPT_FACC NVARCHAR2(6),
    DPT_UDF1 NVARCHAR2(15),
    DPT_UDF2 NVARCHAR2(15),
    DPT_UDF3 NVARCHAR2(15),
    DPT_UDF4 NVARCHAR2(15),
    DPT_UDF5 NVARCHAR2(15),
    DPT_UDF6 NVARCHAR2(15),
    DPT_UDF7 NVARCHAR2(15),
    DPT_UDF8 NVARCHAR2(15),
    DPT_UDF9 NVARCHAR2(15),
    DPT_UDFA NVARCHAR2(15),
    DPT_UDFB NVARCHAR2(15),
    DPT_UDFC NVARCHAR2(15),
    DPT_UDFD NVARCHAR2(15),
    DPT_UDFE NVARCHAR2(15),
    DPT_UDFF NVARCHAR2(15),
    DPT_UDFG NVARCHAR2(15),
    DPT_UDFH NVARCHAR2(15),
    DPT_UDFI NVARCHAR2(15),
    DPT_UDFJ NVARCHAR2(100),
    DPT_UDFK NVARCHAR2(100),
    DPT_DPT1 NVARCHAR2(12),
    DPT_CCOC NVARCHAR2(6)
);

create index INTUIT.INS_DPTI2
    on INTUIT.INS_DPT (DPT_INSC);

create table INTUIT.SRS_FAC
(
    FAC_CODE NVARCHAR2(6) not null
        constraint SRS_FACP1
            primary key,
    FAC_SNAM NVARCHAR2(15),
    FAC_NAME NVARCHAR2(100),
    FAC_IUSE VARCHAR2(1),
    FAC_UDF1 NVARCHAR2(15),
    FAC_UDF2 NVARCHAR2(15),
    FAC_UDF3 NVARCHAR2(15),
    FAC_UDF4 NVARCHAR2(15),
    FAC_UDF5 NVARCHAR2(15),
    FAC_UDF6 NVARCHAR2(15),
    FAC_UDF7 NVARCHAR2(15),
    FAC_UDF8 NVARCHAR2(15),
    FAC_UDF9 NVARCHAR2(15),
    FAC_UDFA NVARCHAR2(15),
    FAC_UDFB NVARCHAR2(15),
    FAC_UDFC NVARCHAR2(15),
    FAC_UDFD NVARCHAR2(15),
    FAC_UDFE NVARCHAR2(15),
    FAC_UDFF NVARCHAR2(15),
    FAC_UDFG NVARCHAR2(15),
    FAC_UDFH NVARCHAR2(15),
    FAC_UDFI NVARCHAR2(15),
    FAC_UDFJ NVARCHAR2(100),
    FAC_UDFK NVARCHAR2(100)
);

create table INTUIT.CAM_LEV
(
    LEV_CODE NVARCHAR2(6) not null
        constraint CAM_LEVP1
            primary key,
    LEV_SNAM NVARCHAR2(15),
    LEV_NAME NVARCHAR2(50),
    LEV_IUSE VARCHAR2(1)
);
create table INTUIT.INS_LCA
(
    LCA_CODE NVARCHAR2(12) not null
        constraint INS_LCAP1
            primary key,
    LCA_SNAM NVARCHAR2(15),
    LCA_NAME NVARCHAR2(50),
    LCA_CMPC NVARCHAR2(1),
    LCA_SITC NVARCHAR2(12),
    LCA_IUSE VARCHAR2(1),
    LCA_LAD1 NVARCHAR2(50),
    LCA_LAD2 NVARCHAR2(50),
    LCA_LAD3 NVARCHAR2(50),
    LCA_LAD4 NVARCHAR2(50),
    LCA_LAD5 NVARCHAR2(50),
    LCA_LAPC NVARCHAR2(12),
    LCA_UDF1 NVARCHAR2(15),
    LCA_UDF2 NVARCHAR2(15),
    LCA_UDF3 NVARCHAR2(15),
    LCA_UDF4 NVARCHAR2(15),
    LCA_UDF5 NVARCHAR2(15),
    LCA_UDF6 NVARCHAR2(15),
    LCA_UDF7 NVARCHAR2(15),
    LCA_UDF8 NVARCHAR2(15),
    LCA_UDF9 NVARCHAR2(15),
    LCA_UDFA NVARCHAR2(15),
    LCA_UDFB NVARCHAR2(15),
    LCA_UDFC NVARCHAR2(15),
    LCA_UDFD NVARCHAR2(15),
    LCA_UDFE NVARCHAR2(15),
    LCA_UDFF NVARCHAR2(15),
    LCA_UDFG NVARCHAR2(15),
    LCA_UDFH NVARCHAR2(15),
    LCA_UDFI NVARCHAR2(15),
    LCA_UDFJ NVARCHAR2(100),
    LCA_UDFK NVARCHAR2(100),
    LCA_STOK VARCHAR2(1),
    LCA_CNTY NVARCHAR2(50),
    LCA_MSRT NVARCHAR2(25),
    LCA_EMAD NVARCHAR2(100),
    LCA_TELN NVARCHAR2(20),
    LCA_HLCC NVARCHAR2(12),
    LCA_LCID NVARCHAR2(15)
);

create index INTUIT.INS_LCAI2
    on INTUIT.INS_LCA (LCA_CMPC);


create table INTUIT.CAM_MDS
(
    MOD_CODE NVARCHAR2(12) not null,
    MDS_SEQN NVARCHAR2(4)  not null,
    MDS_DVNC NVARCHAR2(12),
    MDS_AYRC NVARCHAR2(12),
    MDS_TITL NVARCHAR2(120),
    MDS_UDF1 NVARCHAR2(15),
    MDS_UDF2 NVARCHAR2(15),
    MDS_UDF3 NVARCHAR2(15),
    MDS_UDF4 NVARCHAR2(15),
    MDS_UDF5 NVARCHAR2(15),
    MDS_UDF6 NVARCHAR2(15),
    MDS_UDF7 NVARCHAR2(15),
    MDS_UDF8 NVARCHAR2(15),
    MDS_UDF9 NVARCHAR2(15),
    MDS_UDFA NVARCHAR2(15),
    MDS_UDFB NVARCHAR2(15),
    MDS_UDFC NVARCHAR2(15),
    MDS_UDFD NVARCHAR2(15),
    MDS_UDFE NVARCHAR2(15),
    MDS_UDFF NVARCHAR2(15),
    MDS_UDFG NVARCHAR2(15),
    MDS_UDFH NVARCHAR2(15),
    MDS_UDFI NVARCHAR2(15),
    MDS_UDFJ NVARCHAR2(100),
    MDS_UDFK NVARCHAR2(100),
    MOD_DESC NCLOB,
    MDS_DESV NCLOB,
    constraint CAM_MDSP1
        primary key (MOD_CODE, MDS_SEQN)
);

create index INTUIT.CAM_MDSI2
    on INTUIT.CAM_MDS (MOD_CODE);

create table INTUIT.CAM_MAV
(
    MOD_CODE  NVARCHAR2(12) not null,
    MAV_OCCUR NVARCHAR2(6)  not null,
    AYR_CODE  NVARCHAR2(12) not null,
    PSL_CODE  NVARCHAR2(6)  not null,
    SCH_CODE  NVARCHAR2(6),
    LEV_CODE  NVARCHAR2(6),
    SHS_CODE  NVARCHAR2(6),
    LCA_CODE  NVARCHAR2(12),
    MAV_TRGT  NUMBER(4),
    MAV_ACTL  NUMBER(4),
    MAV_ACTS  NUMBER(4),
    MAV_ACTM  NUMBER(4),
    MAV_CHIN  NUMBER(4),
    MAV_COUT  NUMBER(4),
    MAV_BEGP  NVARCHAR2(1),
    MAV_ENDP  NVARCHAR2(1),
    DAY_CODE  NVARCHAR2(1),
    MAV_STIME DATE,
    MAP_CODE  NVARCHAR2(12),
    MKS_CODE  NVARCHAR2(6),
    MAV_PSEQ  NUMBER(2),
    MAV_WPER  NUMBER(4, 1),
    MAV_GLHR  NUMBER(5),
    MAV_MACC  NVARCHAR2(6),
    DOM_CODE  NVARCHAR2(12),
    PRS_CODE  NVARCHAR2(12),
    MAV_BEGW  NUMBER(2),
    MAV_ENDW  NUMBER(2),
    MAV_TELT  CHAR,
    DPT_CODE  NVARCHAR2(12),
    MAV_DISPA NVARCHAR2(1),
    MAV_TOCC  NVARCHAR2(12),
    MAV_VLYN  VARCHAR2(1),
    MAV_PER1  NUMBER(4),
    MAV_PER2  NUMBER(4),
    MAV_ARNN  NUMBER(6),
    MAV_UDF1  NVARCHAR2(15),
    MAV_UDF2  NVARCHAR2(15),
    MAV_UDF3  NVARCHAR2(15),
    MAV_UDF4  NVARCHAR2(15),
    MAV_UDF5  NVARCHAR2(15),
    MAV_UDF6  NVARCHAR2(15),
    MAV_UDF7  NVARCHAR2(15),
    MAV_UDF8  NVARCHAR2(15),
    MAV_UDF9  NVARCHAR2(15),
    MAV_UDFA  NVARCHAR2(15),
    MAV_UDFB  NVARCHAR2(15),
    MAV_UDFC  NVARCHAR2(15),
    MAV_UDFD  NVARCHAR2(15),
    MAV_UDFE  NVARCHAR2(15),
    MAV_UDFF  NVARCHAR2(15),
    MAV_UDFG  NVARCHAR2(15),
    MAV_UDFH  NVARCHAR2(15),
    MAV_UDFI  NVARCHAR2(15),
    MAV_UDFJ  NVARCHAR2(100),
    MAV_UDFK  NVARCHAR2(100),
    MAV_REGM  NVARCHAR2(1),
    MAV_MAVN  NVARCHAR2(120),
    MAV_HLCC  NVARCHAR2(12),
    MAV_EXMR  NVARCHAR2(1),
    MAV_FRID  VARCHAR2(1),
    MAV_TIII  NVARCHAR2(12),
    MAV_WAIT  VARCHAR2(1),
    MAV_ACTW  NUMBER(4),
    MAV_MAVC  NUMBER(5, 2),
    MAV_ADPC  NVARCHAR2(12),
    constraint CAM_MAVP1
        primary key (MOD_CODE, MAV_OCCUR, AYR_CODE, PSL_CODE)
);

create index INTUIT.CAM_MAVI2
    on INTUIT.CAM_MAV (MOD_CODE);

create index INTUIT.CAM_MAVI3
    on INTUIT.CAM_MAV (AYR_CODE, PSL_CODE);

create index INTUIT.CAM_MAVI4
    on INTUIT.CAM_MAV (SCH_CODE, LEV_CODE);

create index INTUIT.CAM_MAVI5
    on INTUIT.CAM_MAV (MAP_CODE);

create index INTUIT.CAM_MAVI6
    on INTUIT.CAM_MAV (MOD_CODE, AYR_CODE, PSL_CODE);

create index INTUIT.CAM_MAVI7
    on INTUIT.CAM_MAV (PSL_CODE);

create table INTUIT.CAM_TOP
(
    TOP_CODE NVARCHAR2(12) not null
        constraint CAM_TOPP1
            primary key,
    TOP_SNAM NVARCHAR2(15),
    TOP_NAME NVARCHAR2(50),
    TOP_PERC NUMBER(3),
    MOD_CODE NVARCHAR2(12),
    SUB_CODE NVARCHAR2(12),
    DPT_CODE NVARCHAR2(12),
    TOP_IUSE VARCHAR2(1),
    TOP_UDF1 NVARCHAR2(15),
    TOP_UDF2 NVARCHAR2(15),
    TOP_UDF3 NVARCHAR2(15),
    TOP_UDF4 NVARCHAR2(15),
    TOP_UDF5 NVARCHAR2(15),
    TOP_UDF6 NVARCHAR2(15),
    TOP_UDF7 NVARCHAR2(15),
    TOP_UDF8 NVARCHAR2(15),
    TOP_UDF9 NVARCHAR2(15),
    TOP_UDFA NVARCHAR2(15),
    TOP_UDFB NVARCHAR2(15),
    TOP_UDFC NVARCHAR2(15),
    TOP_UDFD NVARCHAR2(15),
    TOP_UDFE NVARCHAR2(15),
    TOP_UDFF NVARCHAR2(15),
    TOP_UDFG NVARCHAR2(15),
    TOP_UDFH NVARCHAR2(15),
    TOP_UDFI NVARCHAR2(15),
    TOP_UDFJ NVARCHAR2(100),
    TOP_UDFK NVARCHAR2(100)
);

create index INTUIT.CAM_TOPI2
    on INTUIT.CAM_TOP (MOD_CODE);

create index INTUIT.CAM_TOPI3
    on INTUIT.CAM_TOP (DPT_CODE);

create index INTUIT.CAM_TOPI4
    on INTUIT.CAM_TOP (SUB_CODE);

create table SRS_CRN
(
    CRN_CRSC NVARCHAR2(15) not null,
    CRN_SEQN NVARCHAR2(4)  not null,
    CRN_DVNC NVARCHAR2(12),
    CRN_AYRC NVARCHAR2(12),
    CRN_TITL NVARCHAR2(120),
    CRN_UDF1 NVARCHAR2(15),
    CRN_UDF2 NVARCHAR2(15),
    CRN_UDF3 NVARCHAR2(15),
    CRN_UDF4 NVARCHAR2(15),
    CRN_UDF5 NVARCHAR2(15),
    CRN_UDF6 NVARCHAR2(15),
    CRN_UDF7 NVARCHAR2(15),
    CRN_UDF8 NVARCHAR2(15),
    CRN_UDF9 NVARCHAR2(15),
    CRN_UDFA NVARCHAR2(15),
    CRN_UDFB NVARCHAR2(15),
    CRN_UDFC NVARCHAR2(15),
    CRN_UDFD NVARCHAR2(15),
    CRN_UDFE NVARCHAR2(15),
    CRN_UDFF NVARCHAR2(15),
    CRN_UDFG NVARCHAR2(15),
    CRN_UDFH NVARCHAR2(15),
    CRN_UDFI NVARCHAR2(15),
    CRN_UDFJ NVARCHAR2(100),
    CRN_UDFK NVARCHAR2(100),
    CRN_DESC NCLOB,
    CRN_DESV NCLOB,
    constraint SRS_CRNP1
        primary key (CRN_CRSC, CRN_SEQN)
);


create table SRS_CBO
(
    CBO_AYRC   NVARCHAR2(12) not null,
    CBO_CRSC   NVARCHAR2(15) not null,
    CBO_BLOK   NVARCHAR2(2)  not null,
    CBO_OCCL   NVARCHAR2(6)  not null,
    CBO_BEGD   DATE,
    CBO_ENDD   DATE,
    CBO_NAYR   NVARCHAR2(12),
    CBO_NCRS   NVARCHAR2(15),
    CBO_NBLK   NVARCHAR2(2),
    CBO_NOCC   NVARCHAR2(6),
    CBO_LCAC   NVARCHAR2(12),
    CBO_ELSC   NVARCHAR2(3),
    CBO_COHC   NVARCHAR2(12),
    CBO_PSLC   NVARCHAR2(6),
    CBO_LEVC   NVARCHAR2(6),
    CBO_CALC   NVARCHAR2(6),
    CBO_DSLD   NUMBER(4, 1),
    CBO_DISD   NUMBER(4, 1),
    CBO_FRN1   NVARCHAR2(3),
    CBO_FRN2   NVARCHAR2(3),
    CBO_EHCF   NVARCHAR2(1),
    CBO_TFIE   NUMBER(11, 2),
    CBO_MOAC   NVARCHAR2(6),
    CBO_TRGT   NUMBER(5),
    CBO_HRWEEK NUMBER(4, 2),
    CBO_WEEKYR NUMBER(3),
    CBO_TOTHR  NUMBER(6, 2),
    CBO_REQD   DATE,
    CBO_EREF   NVARCHAR2(12),
    CBO_PHRS   NUMBER(6, 2),
    CBO_PARC   NVARCHAR2(6),
    CBO_PAR1   NVARCHAR2(6),
    CBO_PAR2   NVARCHAR2(6),
    CBO_VALC   NVARCHAR2(12),
    CBO_DSUM   NUMBER(5, 3),
    CBO_CSUM   NUMBER(8, 3),
    CBO_ASUM   NUMBER(8, 3),
    CBO_EATS   NUMBER(5, 3),
    CBO_EAPS   NUMBER(5, 3),
    CBO_CELS   NUMBER(8, 3),
    CBO_RCYN   NVARCHAR2(1),
    CBO_PTAR   NUMBER(5),
    CBO_CTAR   NUMBER(5),
    CBO_RSRV   NUMBER(5),
    CBO_COFO   NUMBER(5),
    CBO_COFA   NUMBER(5),
    CBO_COFI   NUMBER(5),
    CBO_UOFO   NUMBER(5),
    CBO_UOFA   NUMBER(5),
    CBO_UOFI   NUMBER(5),
    CBO_DIRE   NUMBER(5),
    CBO_RCOA   NUMBER(3),
    CBO_RCOI   NUMBER(3),
    CBO_RCAU   NUMBER(3),
    CBO_RCIU   NUMBER(3),
    CBO_RUOA   NUMBER(3),
    CBO_RUOI   NUMBER(3),
    CBO_RUIA   NUMBER(3),
    CBO_RUAS   NUMBER(3),
    CBO_RDES   NUMBER(3),
    CBO_NCNC   NUMBER(5),
    CBO_NSNC   NUMBER(5),
    CBO_LEFT   NUMBER(5),
    CBO_COLM   NUMBER(5),
    CBO_UOLM   NUMBER(5),
    CBO_AOLM   NUMBER(5),
    CBO_DELM   NUMBER(5),
    CBO_YTYP   NVARCHAR2(1),
    CBO_FNDL   NVARCHAR2(3),
    CBO_CMRT   VARCHAR2(1),
    CBO_CMRA   VARCHAR2(1),
    CBO_NUMR   NUMBER(2),
    CBO_SIZR   NUMBER(3),
    CBO_BEGT   DATE,
    CBO_ENDT   DATE,
    CBO_DURN   NUMBER(4, 2),
    CBO_PRSC   NVARCHAR2(12),
    CBO_ROMC   NVARCHAR2(15),
    CBO_RPFX   NVARCHAR2(6),
    CBO_CPPC   NVARCHAR2(12),
    CBO_EXCC   NVARCHAR2(12),
    CBO_SPIF   NUMBER(6, 3),
    CBO_SPIG   NVARCHAR2(1),
    CBO_CHGR   VARCHAR2(1),
    CBO_LENG   NUMBER(20),
    CBO_PRGP   NUMBER(1),
    CBO_ISTL   VARCHAR2(1),
    CBO_ISLD   DATE,
    CBO_CEPC   NVARCHAR2(12),
    CBO_STAC   NVARCHAR2(6),
    CBO_AYR2   NVARCHAR2(12),
    CBO_PSL2   NVARCHAR2(6),
    CBO_VLYN   VARCHAR2(1),
    CBO_CMPC   NVARCHAR2(1),
    CBO_CMP1   NVARCHAR2(1),
    CBO_UFIP   NVARCHAR2(1),
    CBO_GIN1   NUMBER(2),
    CBO_GIN2   NUMBER(2),
    CBO_UNQN   NUMBER(2),
    CBO_YLEN   NUMBER(2),
    CBO_UOMC   NVARCHAR2(6),
    CBO_UDF1   NVARCHAR2(15),
    CBO_UDF2   NVARCHAR2(15),
    CBO_UDF3   NVARCHAR2(15),
    CBO_UDF4   NVARCHAR2(15),
    CBO_UDF5   NVARCHAR2(15),
    CBO_UDF6   NVARCHAR2(15),
    CBO_UDF7   NVARCHAR2(15),
    CBO_UDF8   NVARCHAR2(15),
    CBO_UDF9   NVARCHAR2(15),
    CBO_UDFA   NVARCHAR2(15),
    CBO_UDFB   NVARCHAR2(15),
    CBO_UDFC   NVARCHAR2(15),
    CBO_UDFD   NVARCHAR2(15),
    CBO_UDFE   NVARCHAR2(15),
    CBO_UDFF   NVARCHAR2(15),
    CBO_UDFG   NVARCHAR2(15),
    CBO_UDFH   NVARCHAR2(15),
    CBO_UDFI   NVARCHAR2(15),
    CBO_UDFJ   NVARCHAR2(100),
    CBO_UDFK   NVARCHAR2(100),
    CBO_CSF1   NVARCHAR2(3),
    CBO_CSF2   NVARCHAR2(3),
    CBO_HCIC   NVARCHAR2(30),
    CBO_MODC   NVARCHAR2(12),
    CBO_MAVO   NVARCHAR2(6),
    CBO_PSL1   NVARCHAR2(6),
    CBO_CLSC   NVARCHAR2(1),
    CBO_COLO   NVARCHAR2(4),
    CBO_TITL   NVARCHAR2(120),
    CBO_FTEA   NUMBER(4, 1),
    CBO_FTEB   NUMBER(4, 1),
    CBO_FTEM   NVARCHAR2(1),
    CBO_TDAT   NUMBER(12),
    CBO_TENR   NUMBER(12),
    CBO_TSUC   NUMBER(12),
    CBO_SRR1   NUMBER(12),
    CBO_SRR2   NUMBER(12),
    CBO_SOUT   NUMBER(12),
    CBO_SPAR   NUMBER(12),
    CBO_SARU   NUMBER(12),
    CBO_DBD1   DATE,
    CBO_DBD2   DATE,
    CBO_DBD3   DATE,
    CBO_DBC1   NUMBER(3),
    CBO_DBC2   NUMBER(3),
    CBO_DBC3   NUMBER(3),
    CBO_DVNC   NVARCHAR2(12),
    CBO_ICLT   NVARCHAR2(2),
    CBO_GPPC   NVARCHAR2(12),
    CBO_CPRC   NVARCHAR2(12),
    CBO_APTY   NVARCHAR2(1),
    CBO_WECI   NVARCHAR2(1),
    CBO_ADPC   NVARCHAR2(12),
    CBO_OPAP   NVARCHAR2(1),
    CBO_SWEC   NVARCHAR2(6),
    CBO_CSID   NVARCHAR2(50),
    CBO_ERFM   NVARCHAR2(1),
    CBO_DLPC   NVARCHAR2(12),
    constraint SRS_CBOP1
        primary key (CBO_AYRC, CBO_CRSC, CBO_BLOK, CBO_OCCL)
);

create index SRS_CBOI2
    on SRS_CBO (CBO_AYRC);

create index SRS_CBOI3
    on SRS_CBO (CBO_CRSC, CBO_BLOK);

create index SRS_CBOI4
    on SRS_CBO (CBO_NAYR);

create index SRS_CBOI5
    on SRS_CBO (CBO_NCRS, CBO_NBLK);

create index SRS_CBOI6
    on SRS_CBO (CBO_NCRS);


create table SRS_VAR
(
    VAR_MCRC NVARCHAR2(15) not null,
    VAR_SEQN NVARCHAR2(4)  not null,
    VAR_SCHC NVARCHAR2(6)  not null,
    VAR_PRGC NVARCHAR2(12) not null,
    VAR_ROUC NVARCHAR2(12) not null,
    VAR_AWDC NVARCHAR2(12),
    VAR_IUSE VARCHAR2(1),
    VAR_UDF1 NVARCHAR2(15),
    VAR_UDF2 NVARCHAR2(15),
    VAR_UDF3 NVARCHAR2(15),
    VAR_UDF4 NVARCHAR2(15),
    VAR_UDF5 NVARCHAR2(15),
    VAR_UDF6 NVARCHAR2(15),
    VAR_UDF7 NVARCHAR2(15),
    VAR_UDF8 NVARCHAR2(15),
    VAR_UDF9 NVARCHAR2(15),
    VAR_UDFA NVARCHAR2(15),
    VAR_UDFB NVARCHAR2(15),
    VAR_UDFC NVARCHAR2(15),
    VAR_UDFD NVARCHAR2(15),
    VAR_UDFE NVARCHAR2(15),
    VAR_UDFF NVARCHAR2(15),
    VAR_UDFG NVARCHAR2(15),
    VAR_UDFH NVARCHAR2(15),
    VAR_UDFI NVARCHAR2(15),
    VAR_UDFJ NVARCHAR2(100),
    VAR_UDFK NVARCHAR2(100),
    constraint SRS_VARP1
        primary key (VAR_MCRC, VAR_SEQN)
);

create index SRS_VARI2
    on SRS_VAR (VAR_MCRC);

create index SRS_VARI3
    on SRS_VAR (VAR_SCHC);

create index SRS_VARI4
    on SRS_VAR (VAR_PRGC);

create index SRS_VARI5
    on SRS_VAR (VAR_ROUC);

create table SRS_VCO
(
    VCO_CRSC NVARCHAR2(15) not null,
    VCO_SEQ6 NUMBER(6)     not null,
    VCO_SCHC NVARCHAR2(6),
    VCO_PRGC NVARCHAR2(12) not null,
    VCO_ROUC NVARCHAR2(12) not null,
    VCO_AWDC NVARCHAR2(12),
    VCO_NAME NVARCHAR2(250),
    VCO_IUSE VARCHAR2(1),
    VCO_RANK NUMBER(4),
    VCO_EXTR NVARCHAR2(24),
    VCO_AYR1 NVARCHAR2(12),
    VCO_AYR2 NVARCHAR2(12),
    VCO_BEGY NUMBER(4),
    VCO_ENDY NUMBER(4),
    VCO_UDF1 NVARCHAR2(15),
    VCO_UDF2 NVARCHAR2(15),
    VCO_UDF3 NVARCHAR2(15),
    VCO_UDF4 NVARCHAR2(15),
    VCO_UDF5 NVARCHAR2(15),
    VCO_UDF6 NVARCHAR2(15),
    VCO_UDF7 NVARCHAR2(15),
    VCO_UDF8 NVARCHAR2(15),
    VCO_UDF9 NVARCHAR2(15),
    VCO_UDFA NVARCHAR2(15),
    VCO_UDFB NVARCHAR2(15),
    VCO_UDFC NVARCHAR2(15),
    VCO_UDFD NVARCHAR2(15),
    VCO_UDFE NVARCHAR2(15),
    VCO_UDFF NVARCHAR2(15),
    VCO_UDFG NVARCHAR2(15),
    VCO_UDFH NVARCHAR2(15),
    VCO_UDFI NVARCHAR2(15),
    VCO_UDFJ NVARCHAR2(100),
    VCO_UDFK NVARCHAR2(100),
    VCO_PDTP NVARCHAR2(255),
    VCO_DYNP NVARCHAR2(255),
    VCO_ERFM NVARCHAR2(1),
    constraint SRS_VCOP1
        primary key (VCO_CRSC, VCO_SEQ6)
);

create table INS_ROE
(
    ROE_ROUC NVARCHAR2(12) not null,
    ROE_SEQ3 NVARCHAR2(3)  not null,
    ROE_PWYC NVARCHAR2(12),
    ROE_UDF1 NVARCHAR2(15),
    ROE_UDF2 NVARCHAR2(15),
    ROE_UDF3 NVARCHAR2(15),
    ROE_UDF4 NVARCHAR2(15),
    ROE_UDF5 NVARCHAR2(15),
    ROE_UDF6 NVARCHAR2(15),
    ROE_UDF7 NVARCHAR2(15),
    ROE_UDF8 NVARCHAR2(15),
    ROE_UDF9 NVARCHAR2(15),
    ROE_UDFA NVARCHAR2(15),
    ROE_UDFB NVARCHAR2(15),
    ROE_UDFC NVARCHAR2(15),
    ROE_UDFD NVARCHAR2(15),
    ROE_UDFE NVARCHAR2(15),
    ROE_UDFF NVARCHAR2(15),
    ROE_UDFG NVARCHAR2(15),
    ROE_UDFH NVARCHAR2(15),
    ROE_UDFI NVARCHAR2(15),
    ROE_UDFJ NVARCHAR2(100),
    ROE_UDFK NVARCHAR2(100),
    ROE_VFRD DATE,
    ROE_VTOD DATE,
    ROE_STAS NVARCHAR2(15),
    ROE_CAT1 NVARCHAR2(15),
    ROE_CAT2 NVARCHAR2(15),
    constraint INS_ROEP1
        primary key (ROE_ROUC, ROE_SEQ3)
);

create index INS_ROEI3
    on INS_ROE (ROE_ROUC);

create index INS_ROEI2
    on INS_ROE (ROE_PWYC);


create table INS_ROU
(
    ROU_CODE NVARCHAR2(12) not null
        constraint INS_ROUP1
            primary key,
    ROU_BLNC NUMBER(1),
    ROU_FPTC NVARCHAR2(12),
    ROU_RUTC NVARCHAR2(6),
    ROU_PSAC NVARCHAR2(12),
    ROU_NAME NVARCHAR2(250),
    ROU_IUSE VARCHAR2(1),
    ROU_UDF1 NVARCHAR2(15),
    ROU_UDF2 NVARCHAR2(15),
    ROU_UDF3 NVARCHAR2(15),
    ROU_UDF4 NVARCHAR2(15),
    ROU_UDF5 NVARCHAR2(15),
    ROU_UDF6 NVARCHAR2(15),
    ROU_UDF7 NVARCHAR2(15),
    ROU_UDF8 NVARCHAR2(15),
    ROU_UDF9 NVARCHAR2(15),
    ROU_UDFA NVARCHAR2(15),
    ROU_UDFB NVARCHAR2(15),
    ROU_UDFC NVARCHAR2(15),
    ROU_UDFD NVARCHAR2(15),
    ROU_UDFE NVARCHAR2(15),
    ROU_UDFF NVARCHAR2(15),
    ROU_UDFG NVARCHAR2(15),
    ROU_UDFH NVARCHAR2(15),
    ROU_UDFI NVARCHAR2(15),
    ROU_UDFJ NVARCHAR2(100),
    ROU_UDFK NVARCHAR2(100),
    ROU_GSPY VARCHAR2(1),
    ROU_UROE VARCHAR2(1),
    ROU_FMCC NVARCHAR2(32),
    ROU_GRRD VARCHAR2(1),
    ROU_ESBC NVARCHAR2(6),
    ROU_ESB2 NVARCHAR2(6),
    ROU_ESB3 NVARCHAR2(6),
    ROU_UPAA NVARCHAR2(1),
    ROU_ESB4 NVARCHAR2(6),
    ROU_ESB5 NVARCHAR2(6),
    ROU_ERFM NVARCHAR2(1)
);

create index INS_ROUI2
    on INS_ROU (ROU_FPTC);

create index INS_ROUI3
    on INS_ROU (ROU_RUTC);

create table SRS_MCR
(
    MCR_CODE NVARCHAR2(15) not null
        constraint SRS_MCRP1
            primary key,
    MCR_SNAM NVARCHAR2(15),
    MCR_NAME NVARCHAR2(50),
    MCR_CGPC NVARCHAR2(12),
    MCR_SCHC NVARCHAR2(6)  not null,
    MCR_CRSC NVARCHAR2(15) not null,
    MCR_BLOK NVARCHAR2(2)  not null,
    MCR_OCCL NVARCHAR2(6)  not null,
    MCR_MOAC NVARCHAR2(6)  not null,
    MCR_AESC NVARCHAR2(1)  not null,
    MCR_UCRS NVARCHAR2(15),
    MCR_UCAM NVARCHAR2(3),
    MCR_UFAC NVARCHAR2(1),
    MCR_SCRS NVARCHAR2(4),
    MCR_ADAR NVARCHAR2(1),
    MCR_DPTC NVARCHAR2(12),
    MCR_PRS1 NVARCHAR2(12),
    MCR_PRS2 NVARCHAR2(12),
    MCR_PHON NVARCHAR2(24),
    MCR_TITL NVARCHAR2(120),
    MCR_PRYN NVARCHAR2(1)  not null,
    MCR_CFYN NVARCHAR2(1)  not null,
    MCR_UVST NVARCHAR2(1),
    MCR_UVAC NVARCHAR2(2),
    MCR_UCST NVARCHAR2(1),
    MCR_MINS NVARCHAR2(4),
    MCR_OLBC NVARCHAR2(12),
    MCR_OLB3 NVARCHAR2(12),
    MCR_FACC NVARCHAR2(6),
    MCR_PRS3 NVARCHAR2(12),
    MCR_ENRM NVARCHAR2(3),
    MCR_APRS NVARCHAR2(1),
    MCR_RECR NVARCHAR2(1),
    MCR_SIPL NVARCHAR2(1),
    MCR_MODF NVARCHAR2(1),
    MCR_DAYR NVARCHAR2(12),
    MCR_DMTH NVARCHAR2(6),
    MCR_IUSE VARCHAR2(1),
    MCR_EXTF VARCHAR2(1),
    MCR_JAEF VARCHAR2(1),
    MCR_DAPP VARCHAR2(1),
    MCR_UDF1 NVARCHAR2(15),
    MCR_UDF2 NVARCHAR2(15),
    MCR_UDF3 NVARCHAR2(15),
    MCR_UDF4 NVARCHAR2(15),
    MCR_UDF5 NVARCHAR2(15),
    MCR_UDF6 NVARCHAR2(15),
    MCR_UDF7 NVARCHAR2(15),
    MCR_UDF8 NVARCHAR2(15),
    MCR_UDF9 NVARCHAR2(15),
    MCR_UDFA NVARCHAR2(15),
    MCR_UDFB NVARCHAR2(15),
    MCR_UDFC NVARCHAR2(15),
    MCR_UDFD NVARCHAR2(15),
    MCR_UDFE NVARCHAR2(15),
    MCR_UDFF NVARCHAR2(15),
    MCR_UDFG NVARCHAR2(15),
    MCR_UDFH NVARCHAR2(15),
    MCR_UDFI NVARCHAR2(15),
    MCR_UDFJ NVARCHAR2(100),
    MCR_UDFK NVARCHAR2(100),
    MCR_RC01 VARCHAR2(1),
    MCR_RC02 VARCHAR2(1),
    MCR_RC03 VARCHAR2(1),
    MCR_RC04 VARCHAR2(1),
    MCR_RC05 VARCHAR2(1),
    MCR_RC06 VARCHAR2(1),
    MCR_RC07 VARCHAR2(1),
    MCR_RC08 VARCHAR2(1),
    MCR_RC09 VARCHAR2(1),
    MCR_RC10 VARCHAR2(1),
    MCR_UC01 NVARCHAR2(1),
    MCR_UC02 NVARCHAR2(1),
    MCR_UC03 NVARCHAR2(1),
    MCR_UC04 NVARCHAR2(1),
    MCR_UC05 NVARCHAR2(1),
    MCR_INSC NVARCHAR2(6),
    MCR_GSMA VARCHAR2(1),
    MCR_MSC1 NVARCHAR2(12),
    MCR_MSC2 NVARCHAR2(12),
    MCR_MSC3 NVARCHAR2(12),
    MCR_MSC4 NVARCHAR2(12),
    MCR_MSC5 NVARCHAR2(12),
    MCR_UTYP NVARCHAR2(1),
    MCR_PCGC NVARCHAR2(15),
    MCR_UPRG NVARCHAR2(7),
    MCR_MDOS NUMBER(2),
    MCR_CMPC NVARCHAR2(1),
    MCR_UGID NVARCHAR2(36),
    MCR_NOTE NCLOB
);

create index SRS_MCRI2
    on SRS_MCR (MCR_CGPC);

create index SRS_MCRI3
    on SRS_MCR (MCR_SCHC);

create index SRS_MCRI4
    on SRS_MCR (MCR_CRSC, MCR_BLOK);

create index SRS_MCRI5
    on SRS_MCR (MCR_CRSC);

create index SRS_MCRI6
    on SRS_MCR (MCR_MOAC);

create index SRS_MCRI7
    on SRS_MCR (MCR_UCRS);

create index SRS_MCRI8
    on SRS_MCR (MCR_DPTC);


create table INS_PWY
(
    PWY_CODE NVARCHAR2(12) not null
        constraint INS_PWYP1
            primary key,
    PWY_SNAM NVARCHAR2(15),
    PWY_NAME NVARCHAR2(150),
    PWY_PWGC NVARCHAR2(6),
    PWY_PWTC NVARCHAR2(6),
    PWY_ESBC NVARCHAR2(6),
    PWY_ESB2 NVARCHAR2(6),
    PWY_ESB3 NVARCHAR2(6),
    PWY_EBAL NVARCHAR2(1),
    PWY_AWDN NVARCHAR2(150),
    PWY_IUSE VARCHAR2(1),
    PWY_UDF1 NVARCHAR2(15),
    PWY_UDF2 NVARCHAR2(15),
    PWY_UDF3 NVARCHAR2(15),
    PWY_UDF4 NVARCHAR2(15),
    PWY_UDF5 NVARCHAR2(15),
    PWY_UDF6 NVARCHAR2(15),
    PWY_UDF7 NVARCHAR2(15),
    PWY_UDF8 NVARCHAR2(15),
    PWY_UDF9 NVARCHAR2(15),
    PWY_UDFA NVARCHAR2(15),
    PWY_UDFB NVARCHAR2(15),
    PWY_UDFC NVARCHAR2(15),
    PWY_UDFD NVARCHAR2(15),
    PWY_UDFE NVARCHAR2(15),
    PWY_UDFF NVARCHAR2(15),
    PWY_UDFG NVARCHAR2(15),
    PWY_UDFH NVARCHAR2(15),
    PWY_UDFI NVARCHAR2(15),
    PWY_UDFJ NVARCHAR2(100),
    PWY_UDFK NVARCHAR2(100),
    PWY_FMCC NVARCHAR2(32),
    PWY_NOTE NVARCHAR2(2000),
    PWY_ESB4 NVARCHAR2(6),
    PWY_ESB5 NVARCHAR2(6)
);

create index INS_PWYI2
    on INS_PWY (PWY_PWGC, PWY_PWTC);

create index INS_PWYI3
    on INS_PWY (PWY_PWGC);

create index INS_PWYI4
    on INS_PWY (PWY_PWTC);


create table SRS_CSD
(
    CSD_CRSC NVARCHAR2(15) not null,
    CSD_BLOK NVARCHAR2(2)  not null,
    CSD_SUBC NVARCHAR2(12) not null,
    CSD_DPTC NVARCHAR2(12) not null,
    CSD_PERC NUMBER(7, 4),
    CSD_EXHR VARCHAR2(1),
    CSD_UDF1 NVARCHAR2(15),
    CSD_UDF2 NVARCHAR2(15),
    CSD_UDF3 NVARCHAR2(15),
    CSD_UDF4 NVARCHAR2(15),
    CSD_UDF5 NVARCHAR2(15),
    CSD_UDF6 NVARCHAR2(15),
    CSD_UDF7 NVARCHAR2(15),
    CSD_UDF8 NVARCHAR2(15),
    CSD_UDF9 NVARCHAR2(15),
    CSD_UDFA NVARCHAR2(15),
    CSD_UDFB NVARCHAR2(15),
    CSD_UDFC NVARCHAR2(15),
    CSD_UDFD NVARCHAR2(15),
    CSD_UDFE NVARCHAR2(15),
    CSD_UDFF NVARCHAR2(15),
    CSD_UDFG NVARCHAR2(15),
    CSD_UDFH NVARCHAR2(15),
    CSD_UDFI NVARCHAR2(15),
    CSD_UDFJ NVARCHAR2(100),
    CSD_UDFK NVARCHAR2(100),
    constraint SRS_CSDP1
        primary key (CSD_CRSC, CSD_BLOK, CSD_SUBC, CSD_DPTC)
);

create index SRS_CSDI2
    on SRS_CSD (CSD_CRSC, CSD_BLOK);

create index SRS_CSDI3
    on SRS_CSD (CSD_CRSC);

create index SRS_CSDI4
    on SRS_CSD (CSD_SUBC);

create index SRS_CSDI5
    on SRS_CSD (CSD_DPTC);


create table SRS_CBK
(
    CBK_CRSC NVARCHAR2(15) not null,
    CBK_BLOK NVARCHAR2(2)  not null,
    CBK_YEAR NUMBER(2),
    CBK_FESR NVARCHAR2(12),
    CBK_FPTC NVARCHAR2(12),
    CBK_FCF1 NUMBER(5, 3),
    CBK_FCF2 NUMBER(5, 3),
    CBK_FCF3 NUMBER(5, 3),
    CBK_CRD1 NUMBER(3),
    CBK_ECL1 NVARCHAR2(3),
    CBK_CRD2 NUMBER(3),
    CBK_ECL2 NVARCHAR2(3),
    CBK_ELVC NVARCHAR2(3),
    CBK_LENW NUMBER(2),
    CBK_WPER NUMBER(4, 1),
    CBK_BITT NUMBER(1),
    CBK_CPPC NVARCHAR2(12),
    CBK_SPIF NUMBER(6, 3),
    CBK_SPIG NVARCHAR2(1),
    CBK_CHGR VARCHAR2(1),
    CBK_LENG NUMBER(1),
    CBK_PRGP NUMBER(1),
    CBK_ISTL VARCHAR2(1),
    CBK_ISLD DATE,
    CBK_CEPC NVARCHAR2(12),
    CBK_UDF1 NVARCHAR2(15),
    CBK_UDF2 NVARCHAR2(15),
    CBK_UDF3 NVARCHAR2(15),
    CBK_UDF4 NVARCHAR2(15),
    CBK_UDF5 NVARCHAR2(15),
    CBK_UDF6 NVARCHAR2(15),
    CBK_UDF7 NVARCHAR2(15),
    CBK_UDF8 NVARCHAR2(15),
    CBK_UDF9 NVARCHAR2(15),
    CBK_UDFA NVARCHAR2(15),
    CBK_UDFB NVARCHAR2(15),
    CBK_UDFC NVARCHAR2(15),
    CBK_UDFD NVARCHAR2(15),
    CBK_UDFE NVARCHAR2(15),
    CBK_UDFF NVARCHAR2(15),
    CBK_UDFG NVARCHAR2(15),
    CBK_UDFH NVARCHAR2(15),
    CBK_UDFI NVARCHAR2(15),
    CBK_UDFJ NVARCHAR2(100),
    CBK_UDFK NVARCHAR2(100),
    CBK_YLEN NUMBER(2),
    CBK_KUSE VARCHAR2(1),
    CBK_YPRG NUMBER(2),
    CBK_KSYR NUMBER(2),
    CBK_FNYR VARCHAR2(1),
    CBK_NOTE NCLOB,
    constraint SRS_CBKP1
        primary key (CBK_CRSC, CBK_BLOK)
);

create index SRS_CBKI2
    on SRS_CBK (CBK_CRSC);

create index SRS_CBKI3
    on SRS_CBK (CBK_FPTC);


create table INS_PRU
(
    PRG_CODE  NVARCHAR2(12) not null,
    ROU_CODE  NVARCHAR2(12) not null,
    PRU_EREF  NVARCHAR2(12),
    PRU_EXTF1 NVARCHAR2(12),
    PRU_EXTF2 NVARCHAR2(12),
    PRU_EXTF3 NVARCHAR2(12),
    PRU_IUSE  VARCHAR2(1),
    PRU_UDF1  NVARCHAR2(15),
    PRU_UDF2  NVARCHAR2(15),
    PRU_UDF3  NVARCHAR2(15),
    PRU_UDF4  NVARCHAR2(15),
    PRU_UDF5  NVARCHAR2(15),
    PRU_UDF6  NVARCHAR2(15),
    PRU_UDF7  NVARCHAR2(15),
    PRU_UDF8  NVARCHAR2(15),
    PRU_UDF9  NVARCHAR2(15),
    PRU_UDFA  NVARCHAR2(15),
    PRU_UDFB  NVARCHAR2(15),
    PRU_UDFC  NVARCHAR2(15),
    PRU_UDFD  NVARCHAR2(15),
    PRU_UDFE  NVARCHAR2(15),
    PRU_UDFF  NVARCHAR2(15),
    PRU_UDFG  NVARCHAR2(15),
    PRU_UDFH  NVARCHAR2(15),
    PRU_UDFI  NVARCHAR2(15),
    PRU_UDFJ  NVARCHAR2(100),
    PRU_UDFK  NVARCHAR2(100),
    constraint INS_PRUP1
        primary key (PRG_CODE, ROU_CODE)
);

create index INS_PRUI2
    on INS_PRU (PRG_CODE);

create index INS_PRUI3
    on INS_PRU (ROU_CODE);

create index INS_PRUI4
    on INS_PRU (PRU_EREF);



create table INS_ESB
(
    ESB_CODE NVARCHAR2(6) not null
        constraint INS_ESBP1
            primary key,
    ESB_SNAM NVARCHAR2(15),
    ESB_NAME NVARCHAR2(120),
    ESB_FILL NVARCHAR2(50),
    ESB_HSID NVARCHAR2(6),
    ESB_SID1 NVARCHAR2(4),
    ESB_SID2 NVARCHAR2(4),
    ESB_IUSE VARCHAR2(1),
    ESB_NSS1 NVARCHAR2(1),
    ESB_NSS2 NVARCHAR2(2),
    ESB_NSS3 NVARCHAR2(3),
    ESB_DESC NVARCHAR2(500),
    ESB_UDF1 NVARCHAR2(15),
    ESB_UDF2 NVARCHAR2(15),
    ESB_UDF3 NVARCHAR2(15),
    ESB_UDF4 NVARCHAR2(15),
    ESB_UDF5 NVARCHAR2(15),
    ESB_UDF6 NVARCHAR2(15),
    ESB_UDF7 NVARCHAR2(15),
    ESB_UDF8 NVARCHAR2(15),
    ESB_UDF9 NVARCHAR2(15),
    ESB_UDFA NVARCHAR2(15),
    ESB_UDFB NVARCHAR2(15),
    ESB_UDFC NVARCHAR2(15),
    ESB_UDFD NVARCHAR2(15),
    ESB_UDFE NVARCHAR2(15),
    ESB_UDFF NVARCHAR2(15),
    ESB_UDFG NVARCHAR2(15),
    ESB_UDFH NVARCHAR2(15),
    ESB_UDFI NVARCHAR2(15),
    ESB_UDFJ NVARCHAR2(100),
    ESB_UDFK NVARCHAR2(100),
    ESB_HECS NVARCHAR2(6),
    ESB_ATAS VARCHAR2(1)
)
;

create table INS_MOA
(
    MOA_CODE NVARCHAR2(6) not null
        constraint INS_MOAP1
            primary key,
    MOA_SNAM NVARCHAR2(15),
    MOA_NAME NVARCHAR2(50),
    MOA_FTEV NUMBER(4, 3),
    MOA_HEMA NUMBER(2),
    MOA_FEMA NUMBER(2),
    MOA_FCMA NUMBER(2),
    MOA_FDYN NVARCHAR2(1) not null,
    MOA_UMOA NVARCHAR2(1),
    MOA_FESR NVARCHAR2(6),
    MOA_DWGT NUMBER(6, 3),
    MOA_EDID NUMBER(2),
    MOA_NBMC NVARCHAR2(6),
    MOA_EDIR NVARCHAR2(6),
    MOA_IUSE VARCHAR2(1),
    MOA_UDF1 NVARCHAR2(15),
    MOA_UDF2 NVARCHAR2(15),
    MOA_UDF3 NVARCHAR2(15),
    MOA_UDF4 NVARCHAR2(15),
    MOA_UDF5 NVARCHAR2(15),
    MOA_UDF6 NVARCHAR2(15),
    MOA_UDF7 NVARCHAR2(15),
    MOA_UDF8 NVARCHAR2(15),
    MOA_UDF9 NVARCHAR2(15),
    MOA_UDFA NVARCHAR2(15),
    MOA_UDFB NVARCHAR2(15),
    MOA_UDFC NVARCHAR2(15),
    MOA_UDFD NVARCHAR2(15),
    MOA_UDFE NVARCHAR2(15),
    MOA_UDFF NVARCHAR2(15),
    MOA_UDFG NVARCHAR2(15),
    MOA_UDFH NVARCHAR2(15),
    MOA_UDFI NVARCHAR2(15),
    MOA_UDFJ NVARCHAR2(100),
    MOA_UDFK NVARCHAR2(100)
)
;


create table SRS_ELS
(
    ELS_CODE NVARCHAR2(3) not null
        constraint SRS_ELSP1
            primary key,
    ELS_SNAM NVARCHAR2(15),
    ELS_NAME NVARCHAR2(50),
    ELS_HLID NVARCHAR2(2),
    ELS_FEID NVARCHAR2(2),
    ELS_IUSE VARCHAR2(1)
)
;

create table SRS_COH
(
    COH_CODE NVARCHAR2(12) not null
        constraint SRS_COHP1
            primary key,
    COH_SNAM NVARCHAR2(15),
    COH_NAME NVARCHAR2(50),
    COH_IUSE VARCHAR2(1),
    COH_UDF1 NVARCHAR2(15),
    COH_UDF2 NVARCHAR2(15),
    COH_UDF3 NVARCHAR2(15),
    COH_UDF4 NVARCHAR2(15),
    COH_UDF5 NVARCHAR2(15),
    COH_UDF6 NVARCHAR2(15),
    COH_UDF7 NVARCHAR2(15),
    COH_UDF8 NVARCHAR2(15),
    COH_UDF9 NVARCHAR2(15),
    COH_UDFA NVARCHAR2(15),
    COH_UDFB NVARCHAR2(15),
    COH_UDFC NVARCHAR2(15),
    COH_UDFD NVARCHAR2(15),
    COH_UDFE NVARCHAR2(15),
    COH_UDFF NVARCHAR2(15),
    COH_UDFG NVARCHAR2(15),
    COH_UDFH NVARCHAR2(15),
    COH_UDFI NVARCHAR2(15),
    COH_UDFJ NVARCHAR2(100),
    COH_UDFK NVARCHAR2(100)
)
;


create table INS_SCH
(
    SCH_CODE NVARCHAR2(6) not null
        constraint INS_SCHP1
            primary key,
    SCH_SNAM NVARCHAR2(15),
    SCH_NAME NVARCHAR2(50),
    SCH_FTE  NUMBER(9, 8),
    SCH_EREF NVARCHAR2(12),
    SCH_CATS NVARCHAR2(1),
    SCH_ECCF NUMBER(5, 3),
    SCH_FILR NVARCHAR2(14)
)
;


create table SRS_UOM
(
    UOM_CODE NVARCHAR2(6) not null
        constraint SRS_UOMP1
            primary key,
    UOM_SNAM NVARCHAR2(15),
    UOM_NAME NVARCHAR2(50),
    UOM_HEID NVARCHAR2(2)
)
;


create table INS_PRG
(
    PRG_CODE NVARCHAR2(12) not null
        constraint INS_PRGP1
            primary key,
    PRG_SNAM NVARCHAR2(15),
    PRG_NAME NVARCHAR2(50),
    PRG_SCHC NVARCHAR2(6),
    PRG_IUSE VARCHAR2(1),
    PRG_UDF1 NVARCHAR2(15),
    PRG_UDF2 NVARCHAR2(15),
    PRG_UDF3 NVARCHAR2(15),
    PRG_UDF4 NVARCHAR2(15),
    PRG_UDF5 NVARCHAR2(15),
    PRG_UDF6 NVARCHAR2(15),
    PRG_UDF7 NVARCHAR2(15),
    PRG_UDF8 NVARCHAR2(15),
    PRG_UDF9 NVARCHAR2(15),
    PRG_UDFA NVARCHAR2(15),
    PRG_UDFB NVARCHAR2(15),
    PRG_UDFC NVARCHAR2(15),
    PRG_UDFD NVARCHAR2(15),
    PRG_UDFE NVARCHAR2(15),
    PRG_UDFF NVARCHAR2(15),
    PRG_UDFG NVARCHAR2(15),
    PRG_UDFH NVARCHAR2(15),
    PRG_UDFI NVARCHAR2(15),
    PRG_UDFJ NVARCHAR2(100),
    PRG_UDFK NVARCHAR2(100),
    PRG_MAWD VARCHAR2(1),
    PRG_AXCR VARCHAR2(1),
    PRG_FMCC NVARCHAR2(32),
    PRG_XCRC NVARCHAR2(12),
    PRG_CPRG VARCHAR2(1),
    PRG_PWYP VARCHAR2(1),
    PRG_UAST VARCHAR2(1)
)
;

create index INS_PRGI2
    on INS_PRG (PRG_SCHC)
;

-- auto-generated definition
create table CAM_FMC
(
    FMC_CODE NVARCHAR2(32) not null
        constraint CAM_FMCP1
            primary key,
    FMC_SNAM NVARCHAR2(15),
    FMC_NAME NVARCHAR2(120),
    FMC_IUSE VARCHAR2(1),
    FMC_UDF1 NVARCHAR2(15),
    FMC_UDF2 NVARCHAR2(15),
    FMC_UDF3 NVARCHAR2(15),
    FMC_UDF4 NVARCHAR2(15),
    FMC_UDF5 NVARCHAR2(15),
    FMC_UDF6 NVARCHAR2(15),
    FMC_UDF7 NVARCHAR2(15),
    FMC_UDF8 NVARCHAR2(15),
    FMC_UDF9 NVARCHAR2(15),
    FMC_UDFA NVARCHAR2(15),
    FMC_UDFB NVARCHAR2(15),
    FMC_UDFC NVARCHAR2(15),
    FMC_UDFD NVARCHAR2(15),
    FMC_UDFE NVARCHAR2(15),
    FMC_UDFF NVARCHAR2(15),
    FMC_UDFG NVARCHAR2(15),
    FMC_UDFH NVARCHAR2(15),
    FMC_UDFI NVARCHAR2(15),
    FMC_UDFJ NVARCHAR2(100),
    FMC_UDFK NVARCHAR2(100)
)
;


-- auto-generated definition
create table CAM_FME
(
    FMC_CODE NVARCHAR2(32) not null,
    FME_SEQ  NVARCHAR2(3)  not null,
    FME_MODP NVARCHAR2(12),
    SCH_CODE NVARCHAR2(6),
    LEV_CODE NVARCHAR2(6),
    MTC_CODE NVARCHAR2(6),
    constraint CAM_FMEP1
        primary key (FMC_CODE, FME_SEQ)
)
;

create index CAM_FMEI2
    on CAM_FME (SCH_CODE)
;

create index CAM_FMEI3
    on CAM_FME (LEV_CODE)
;

create index CAM_FMEI4
    on CAM_FME (MTC_CODE)
;

create index CAM_FMEI5
    on CAM_FME (FME_MODP)
;

create index CAM_FMEI6
    on CAM_FME (FMC_CODE)
;


-- auto-generated definition
create table CAM_PDM
(
    PDM_PDTC NVARCHAR2(32) not null,
    PDM_SEQN NVARCHAR2(3)  not null,
    PDM_MODC NVARCHAR2(12),
    PDM_MAVO NVARCHAR2(6),
    PDM_YEAR NUMBER(1),
    PDM_PSLC NVARCHAR2(6),
    PDM_SESC NVARCHAR2(6),
    PDM_ACTS VARCHAR2(1),
    PDM_AUTS VARCHAR2(1),
    PDM_RANK NVARCHAR2(2),
    PDM_SLEV VARCHAR2(1),
    PDM_MCRD NVARCHAR2(6),
    PDM_PSST VARCHAR2(1),
    PDM_AGRP NVARCHAR2(2),
    PDM_SGRP NVARCHAR2(12),
    PDM_DATA NVARCHAR2(3),
    PDM_FMCC NVARCHAR2(32),
    PDM_MINV NUMBER(5, 2),
    PDM_MAXV NUMBER(5, 2),
    PDM_REGS VARCHAR2(1),
    PDM_REGM VARCHAR2(1),
    PDM_OPER VARCHAR2(3),
    PDM_APPY VARCHAR2(1),
    PDM_GRPN NVARCHAR2(12),
    PDM_GMIN NUMBER(5, 2),
    PDM_GMAX NUMBER(5, 2),
    PDM_OPNB NVARCHAR2(6),
    PDM_CLSB NVARCHAR2(6),
    PDM_IRNK VARCHAR2(1),
    PDM_TYPE VARCHAR2(3),
    PDM_IUSE VARCHAR2(1),
    PDM_IGEX VARCHAR2(1),
    PDM_AFIL VARCHAR2(1),
    PDM_FMCN NVARCHAR2(120),
    PDM_USTA NVARCHAR2(12),
    PDM_RKYN VARCHAR2(1),
    PDM_WLYN VARCHAR2(1),
    PDM_UDF1 NVARCHAR2(15),
    PDM_UDF2 NVARCHAR2(15),
    PDM_UDF3 NVARCHAR2(15),
    PDM_UDF4 NVARCHAR2(15),
    PDM_UDF5 NVARCHAR2(15),
    PDM_UDF6 NVARCHAR2(15),
    PDM_UDF7 NVARCHAR2(15),
    PDM_UDF8 NVARCHAR2(15),
    PDM_UDF9 NVARCHAR2(15),
    PDM_UDFA NVARCHAR2(15),
    PDM_UDFB NVARCHAR2(15),
    PDM_UDFC NVARCHAR2(15),
    PDM_UDFD NVARCHAR2(15),
    PDM_UDFE NVARCHAR2(15),
    PDM_UDFF NVARCHAR2(15),
    PDM_UDFG NVARCHAR2(15),
    PDM_UDFH NVARCHAR2(15),
    PDM_UDFI NVARCHAR2(15),
    PDM_UDFJ NVARCHAR2(100),
    PDM_UDFK NVARCHAR2(100),
    PDM_DORD NUMBER(3),
    PDM_GDAT NVARCHAR2(3),
    PDM_DESC NCLOB,
    PDM_UHLP NCLOB,
    constraint CAM_PDMP1
        primary key (PDM_PDTC, PDM_SEQN)
)
;

create index CAM_PDMI2
    on CAM_PDM (PDM_FMCC)
;

create table CAM_PDT
(
    PDT_CODE NVARCHAR2(32) not null
        constraint CAM_PDTP1
            primary key,
    PDT_MATC VARCHAR2(1)   not null,
    PDT_TYPE VARCHAR2(1)   not null,
    PDT_PWYC NVARCHAR2(12),
    PDT_PRGC NVARCHAR2(12),
    PDT_ROUC NVARCHAR2(12),
    PDT_AYRC NVARCHAR2(12),
    PDT_CRSC NVARCHAR2(15),
    PDT_BLOK NVARCHAR2(2),
    PDT_OCCL NVARCHAR2(6),
    PDT_PRDC NVARCHAR2(6)  not null,
    PDT_IUSE VARCHAR2(1),
    PDT_SCEE VARCHAR2(1),
    PDT_LVCC NVARCHAR2(6),
    PDT_MACC NVARCHAR2(6),
    PDT_LCAC NVARCHAR2(12),
    PDT_BATC NVARCHAR2(12),
    PDT_SCHG NVARCHAR2(3),
    PDT_RANK NVARCHAR2(2),
    PDT_UDF1 NVARCHAR2(15),
    PDT_UDF2 NVARCHAR2(15),
    PDT_UDF3 NVARCHAR2(15),
    PDT_UDF4 NVARCHAR2(15),
    PDT_UDF5 NVARCHAR2(15),
    PDT_UDF6 NVARCHAR2(15),
    PDT_UDF7 NVARCHAR2(15),
    PDT_UDF8 NVARCHAR2(15),
    PDT_UDF9 NVARCHAR2(15),
    PDT_UDFA NVARCHAR2(15),
    PDT_UDFB NVARCHAR2(15),
    PDT_UDFC NVARCHAR2(15),
    PDT_UDFD NVARCHAR2(15),
    PDT_UDFE NVARCHAR2(15),
    PDT_UDFF NVARCHAR2(15),
    PDT_UDFG NVARCHAR2(15),
    PDT_UDFH NVARCHAR2(15),
    PDT_UDFI NVARCHAR2(15),
    PDT_UDFJ NVARCHAR2(100),
    PDT_UDFK NVARCHAR2(100),
    PDT_TLES VARCHAR2(1),
    PDT_PDRC NVARCHAR2(32),
    PDT_ATTN NUMBER(2),
    PDT_RMIN NUMBER(6),
    PDT_RMAX NUMBER(6),
    PDT_RTYP NVARCHAR2(12),
    PDT_DORD NUMBER(3),
    PDT_UHLP NCLOB,
    PDT_DESC NCLOB
)
    ;


create table INS_PRD
(
    PRD_CODE NVARCHAR2(6) not null
        constraint INS_PRDP1
            primary key,
    PRD_SNAM NVARCHAR2(15),
    PRD_NAME NVARCHAR2(50),
    PRD_PRDS NUMBER(3),
    PRD_IUSE VARCHAR2(1)
)
    ;

