DROP SCHEMA IF EXISTS INTUIT CASCADE;
CREATE SCHEMA INTUIT;
SET SCHEMA INTUIT;

CREATE TABLE INS_MOD
(
    MOD_CODE  NVARCHAR2(12) not null
        constraint INS_MODP1
            primary key,
    DOM_CODE  NVARCHAR2(12),
    MOD_SNAM  NVARCHAR2(15),
    MOD_NAME  NVARCHAR2(120),
    SCH_CODE  NVARCHAR2(6),
    LEV_CODE  NVARCHAR2(6),
    PRS_CODE  NVARCHAR2(12),
    MOT_CODE  NVARCHAR2(6),
    MOD_CRDT  NUMBER(5, 2),
    MOD_HOURS NUMBER(4),
    MAP_CODE  NVARCHAR2(12),
    MOD_EREF  NVARCHAR2(12),
    MKS_CODE  NVARCHAR2(6),
    FPT_CODE  NVARCHAR2(12),
    ESB_CODE  NVARCHAR2(6),
    MOD_NPER  NUMBER(2),
    MOD_MOAS  NVARCHAR2(1),
    MOD_PMOA  NVARCHAR2(1),
    MEP_CODE  NVARCHAR2(6),
    DPT_CODE  NVARCHAR2(12),
    ELV_CODE  NVARCHAR2(3),
    ECL_CODE  NVARCHAR2(3),
    MOD_UTYC  NVARCHAR2(3),
    MOD_COGC  NVARCHAR2(6),
    MOD_STAT  VARCHAR2(1),
    MOD_UPDD  DATE,
    MOD_KEYW  NVARCHAR2(100),
    MOD_IUSE  VARCHAR2(1),
    MOD_TOCC  NVARCHAR2(12),
    MOD_DVNC  NVARCHAR2(12),
    MOD_UDF1  NVARCHAR2(15),
    MOD_UDF2  NVARCHAR2(15),
    MOD_UDF3  NVARCHAR2(15),
    MOD_UDF4  NVARCHAR2(15),
    MOD_UDF5  NVARCHAR2(15),
    MOD_UDF6  NVARCHAR2(15),
    MOD_UDF7  NVARCHAR2(15),
    MOD_UDF8  NVARCHAR2(15),
    MOD_UDF9  NVARCHAR2(15),
    MOD_UDFA  NVARCHAR2(15),
    MOD_UDFB  NVARCHAR2(15),
    MOD_UDFC  NVARCHAR2(15),
    MOD_UDFD  NVARCHAR2(15),
    MOD_UDFE  NVARCHAR2(15),
    MOD_UDFF  NVARCHAR2(15),
    MOD_UDFG  NVARCHAR2(15),
    MOD_UDFH  NVARCHAR2(15),
    MOD_UDFI  NVARCHAR2(15),
    MOD_UDFJ  NVARCHAR2(100),
    MOD_UDFK  NVARCHAR2(100),
    MOD_VALC  NVARCHAR2(12),
    MOD_APRT  NUMBER(5, 2),
    MOD_LANG  NVARCHAR2(1),
    MOD_ERFM  NVARCHAR2(1),
    MOD_MUSE  VARCHAR2(1),
    MOD_FACC  NVARCHAR2(6),
    MOD_ISGX  VARCHAR2(1),
    MOD_REGM  NVARCHAR2(1),
    MOD_FRID  VARCHAR2(1),
    MOD_WEEI  NVARCHAR2(1),
    MOD_MODE  NVARCHAR2(1),
    MOD_ARPT  VARCHAR2(1),
    MOD_NOTE  NCLOB
);

create table INTUIT.CAM_MAB
(
    MAP_CODE  NVARCHAR2(12) not null,
    MAB_SEQ   NVARCHAR2(3)  not null,
    AST_CODE  NVARCHAR2(6),
    MAB_PERC  NUMBER(4),
    MAB_TSHA  NUMBER(5),
    MAB_NAME  NVARCHAR2(120),
    MAB_DDAY  NUMBER(1),
    MAB_DWEEK NUMBER(2),
    MAB_DPRD  NUMBER(2),
    MAB_HOURS NUMBER(5, 2),
    MKS_CODE  NVARCHAR2(6),
    MAB_QMARK NUMBER(7),
    MAB_QSET  NVARCHAR2(2),
    MAB_AGRP  NVARCHAR2(2),
    MAB_RGRP  NVARCHAR2(2),
    MAB_RASI  NVARCHAR2(2),
    MAB_APAC  NVARCHAR2(12),
    MAB_ADVC  NVARCHAR2(12),
    MAB_BRIC  NVARCHAR2(16),
    MAB_EXBD  DATE,
    MAB_EREF  NVARCHAR2(12),
    MAB_HMRK  NVARCHAR2(1),
    MAB_USCD  NVARCHAR2(1),
    MAB_MCDF  NVARCHAR2(1),
    MAB_GGFM  NVARCHAR2(1),
    MAB_DUAW  VARCHAR2(1),
    MAB_PNAM  NVARCHAR2(1),
    MAB_STAD  NVARCHAR2(1),
    MAB_SORT  NVARCHAR2(30),
    MAB_NUSE  VARCHAR2(1),
    MAB_ELOG  VARCHAR2(1),
    MAB_DURM  VARCHAR2(1),
    MAB_UDF1  NVARCHAR2(15),
    MAB_UDF2  NVARCHAR2(15),
    MAB_UDF3  NVARCHAR2(15),
    MAB_UDF4  NVARCHAR2(15),
    MAB_UDF5  NVARCHAR2(15),
    MAB_UDF6  NVARCHAR2(15),
    MAB_UDF7  NVARCHAR2(15),
    MAB_UDF8  NVARCHAR2(15),
    MAB_UDF9  NVARCHAR2(15),
    MAB_UDFA  NVARCHAR2(15),
    MAB_UDFB  NVARCHAR2(15),
    MAB_UDFC  NVARCHAR2(15),
    MAB_UDFD  NVARCHAR2(15),
    MAB_UDFE  NVARCHAR2(15),
    MAB_UDFF  NVARCHAR2(15),
    MAB_UDFG  NVARCHAR2(15),
    MAB_UDFH  NVARCHAR2(15),
    MAB_UDFI  NVARCHAR2(15),
    MAB_UDFJ  NVARCHAR2(100),
    MAB_UDFK  NVARCHAR2(100),
    MAB_LOCK  VARCHAR2(1),
    MAB_IUSE  VARCHAR2(1),
    MAB_AQHC  NVARCHAR2(16),
    MAB_AQH1  NVARCHAR2(16),
    MAB_CGRP  NVARCHAR2(6),
    MAB_FAYN  VARCHAR2(1),
    MAB_GMTH  NVARCHAR2(1),
    MAB_GSTU  NUMBER(3),
    MAB_GINI  NUMBER(2),
    MAB_GMAX  NUMBER(2),
    MAB_DUET  DATE,
    MAB_IRQP  VARCHAR2(1),
    MAB_DTYC  NVARCHAR2(32),
    MAB_FBOC  NVARCHAR2(12),
    MAB_TIIC  NVARCHAR2(16),
    MAB_PRCC  NVARCHAR2(12),
    MAB_ASID  NVARCHAR2(12),
    MAB_HOHM  DATE,
    MAB_DOUB  VARCHAR2(1),
    constraint CAM_MABP1
        primary key (MAP_CODE, MAB_SEQ)
)
;

create index INTUIT.CAM_MABI2
    on INTUIT.CAM_MAB (AST_CODE)
;

create index INTUIT.CAM_MABI3
    on INTUIT.CAM_MAB (MKS_CODE)
;

create index INTUIT.CAM_MABI4
    on INTUIT.CAM_MAB (MAP_CODE)
;

create index INTUIT.CAM_MABI5
    on INTUIT.CAM_MAB (MAB_EREF)
;

create index INTUIT.CAM_MABI6
    on INTUIT.CAM_MAB (MAB_APAC)
;

create index INTUIT.CAM_MABI7
    on INTUIT.CAM_MAB (MAB_APAC, MAB_ADVC)
;

create index INTUIT.CAM_MABI8
    on INTUIT.CAM_MAB (MAB_ASID)
;


create table INTUIT.CAM_APA
(
    APA_CODE NVARCHAR2(12) not null
        constraint CAM_APAP1
            primary key,
    APA_SNAM NVARCHAR2(15),
    APA_NAME NVARCHAR2(50),
    APA_PRSC NVARCHAR2(12),
    APA_APSC NVARCHAR2(6)  not null,
    APA_APTC NVARCHAR2(6)  not null,
    APA_ROMC NVARCHAR2(15),
    APA_NOTE NVARCHAR2(2000),
    APA_SEAT NUMBER(2),
    APA_MSCC NVARCHAR2(12),
    APA_WJRC NVARCHAR2(12),
    APA_MSCP VARCHAR2(1),
    APA_WJRP VARCHAR2(1),
    APA_SGVN VARCHAR2(1),
    APA_APDC NVARCHAR2(12),
    APA_PWGT NUMBER(5, 2)
)
;

create index INTUIT.CAM_APAI2
    on INTUIT.CAM_APA (APA_PRSC)
;

create index INTUIT.CAM_APAI3
    on INTUIT.CAM_APA (APA_APSC)
;

create index INTUIT.CAM_APAI4
    on INTUIT.CAM_APA (APA_ROMC)
;

create table INTUIT.CAM_ADV
(
    ADV_APAC NVARCHAR2(12) not null,
    ADV_CODE NVARCHAR2(12) not null,
    ADV_SNAM NVARCHAR2(15),
    ADV_DURA DATE,
    ADV_RDTM DATE,
    ADV_NUMQ NUMBER(2),
    ADV_MAXQ NUMBER(2),
    ADV_MINQ NUMBER(2),
    ADV_MFEE NUMBER(15, 2),
    ADV_NOTE NVARCHAR2(2000),
    constraint CAM_ADVP1
        primary key (ADV_APAC, ADV_CODE)
)
;

create index INTUIT.CAM_ADVI2
    on INTUIT.CAM_ADV (ADV_APAC)
;

create table INTUIT.CAM_ADR
(
    ADR_APAC NVARCHAR2(12) not null,
    ADR_ADVC NVARCHAR2(12) not null,
    ADR_SEQN NVARCHAR2(3)  not null,
    ADR_ARQC NVARCHAR2(6)  not null,
    ADR_NUMO NUMBER(20)    not null,
    constraint CAM_ADRP1
        primary key (ADR_APAC, ADR_ADVC, ADR_SEQN)
)
;

create index INTUIT.CAM_ADRI2
    on INTUIT.CAM_ADR (ADR_APAC, ADR_ADVC)
;

create index INTUIT.CAM_ADRI3
    on INTUIT.CAM_ADR (ADR_APAC)
;

create index INTUIT.CAM_ADRI4
    on INTUIT.CAM_ADR (ADR_ARQC)
;

create table INTUIT.CAM_ARQ
(
    ARQ_CODE NVARCHAR2(6) not null
        constraint CAM_ARQP1
            primary key,
    ARQ_SNAM NVARCHAR2(15),
    ARQ_NAME NVARCHAR2(255),
    ARQ_ARTC NVARCHAR2(6) not null
)
;

create index INTUIT.CAM_ARQI2
    on INTUIT.CAM_ARQ (ARQ_ARTC)
;
create table INTUIT.CAM_MAP
(
    MAP_CODE  NVARCHAR2(12) not null
        constraint CAM_MAPP1
            primary key,
    MAP_SNAM  NVARCHAR2(15),
    MAP_NAME  NVARCHAR2(50),
    MKS2_CODE NVARCHAR2(6),
    MKS3_CODE NVARCHAR2(6),
    MAP_HIGM  NVARCHAR2(1),
    MAP_AGRP  NVARCHAR2(2),
    MAP_PNAME NVARCHAR2(1),
    MAP_MMSC  NVARCHAR2(6),
    MAP_USCD  NVARCHAR2(1),
    MAP_MCDF  NVARCHAR2(1),
    MAP_GGFM  NVARCHAR2(1),
    MAP_TMRF  CHAR,
    MAP_REAL  CHAR,
    MAP_C100  CHAR,
    MAP_MXRI  NUMBER(1),
    MAP_AWRI  VARCHAR2(1),
    MAP_MWRI  VARCHAR2(1),
    MAP_WMODE NVARCHAR2(1),
    MAP_SCDF  NVARCHAR2(1),
    MAP_SORT  NVARCHAR2(30),
    MAP_ARIS  VARCHAR2(1),
    MAP_TACT  NVARCHAR2(6),
    MAP_PMRK  NVARCHAR2(6),
    MAP_IUSE  VARCHAR2(1),
    MAP_LOCK  VARCHAR2(1),
    MAP_UMRK  VARCHAR2(1),
    MAP_MHCC  NVARCHAR2(16),
    MAP_RASM  VARCHAR2(1),
    MAP_USDR  VARCHAR2(1),
    MAP_AEGR  VARCHAR2(1),
    MAP_UDF1  NVARCHAR2(15),
    MAP_UDF2  NVARCHAR2(15),
    MAP_UDF3  NVARCHAR2(15),
    MAP_UDF4  NVARCHAR2(15),
    MAP_UDF5  NVARCHAR2(15),
    MAP_UDF6  NVARCHAR2(15),
    MAP_UDF7  NVARCHAR2(15),
    MAP_UDF8  NVARCHAR2(15),
    MAP_UDF9  NVARCHAR2(15),
    MAP_UDFA  NVARCHAR2(15),
    MAP_UDFB  NVARCHAR2(15),
    MAP_UDFC  NVARCHAR2(15),
    MAP_UDFD  NVARCHAR2(15),
    MAP_UDFE  NVARCHAR2(15),
    MAP_UDFF  NVARCHAR2(15),
    MAP_UDFG  NVARCHAR2(15),
    MAP_UDFH  NVARCHAR2(15),
    MAP_UDFI  NVARCHAR2(15),
    MAP_UDFJ  NVARCHAR2(100),
    MAP_UDFK  NVARCHAR2(100),
    MAP_DAQE  NVARCHAR2(1)
)
;

create index INTUIT.CAM_MAPI2
    on INTUIT.CAM_MAP (MKS2_CODE)
;

create index INTUIT.CAM_MAPI3
    on INTUIT.CAM_MAP (MKS3_CODE)
;

create table INTUIT.CAM_AST
(
    AST_CODE  NVARCHAR2(6) not null
        constraint CAM_ASTP1
            primary key,
    AST_SNAM  NVARCHAR2(15),
    AST_NAME  NVARCHAR2(50),
    AST_GENDD NVARCHAR2(1),
    AST_PNAME NVARCHAR2(1),
    AST_RECLD NVARCHAR2(1),
    AST_PNAM  NVARCHAR2(1),
    AST_MKSC  NVARCHAR2(6),
    AST_USCD  NVARCHAR2(1),
    AST_MCDF  NVARCHAR2(1),
    AST_GGFM  NVARCHAR2(1),
    AST_STAD  NVARCHAR2(1),
    AST_SORT  NVARCHAR2(30),
    AST_EXDY  NUMBER(2),
    AST_IUSE  VARCHAR2(1),
    AST_UDF1  NVARCHAR2(15),
    AST_UDF2  NVARCHAR2(15),
    AST_UDF3  NVARCHAR2(15),
    AST_UDF4  NVARCHAR2(15),
    AST_UDF5  NVARCHAR2(15),
    AST_UDF6  NVARCHAR2(15),
    AST_UDF7  NVARCHAR2(15),
    AST_UDF8  NVARCHAR2(15),
    AST_UDF9  NVARCHAR2(15),
    AST_UDFA  NVARCHAR2(15),
    AST_UDFB  NVARCHAR2(15),
    AST_UDFC  NVARCHAR2(15),
    AST_UDFD  NVARCHAR2(15),
    AST_UDFE  NVARCHAR2(15),
    AST_UDFF  NVARCHAR2(15),
    AST_UDFG  NVARCHAR2(15),
    AST_UDFH  NVARCHAR2(15),
    AST_UDFI  NVARCHAR2(15),
    AST_UDFJ  NVARCHAR2(100),
    AST_UDFK  NVARCHAR2(100)
)
;


create table INTUIT.SRS_CRS
(
    CRS_CODE   NVARCHAR2(15) not null
        constraint SRS_CRSP1
            primary key,
    CRS_SNAM   NVARCHAR2(15),
    CRS_NAME   NVARCHAR2(50),
    CRS_TITL   NVARCHAR2(120),
    CRS_CGPC   NVARCHAR2(12),
    CRS_DPTC   NVARCHAR2(12),
    CRS_PRSC   NVARCHAR2(12),
    CRS_SCHC   NVARCHAR2(6),
    CRS_COSC   NVARCHAR2(6),
    CRS_TOPC   NVARCHAR2(3),
    CRS_MOEN   NVARCHAR2(2),
    CRS_BEGD   DATE,
    CRS_ENDD   DATE,
    CRS_YLEN   NUMBER(2),
    CRS_FPTC   NVARCHAR2(12),
    CRS_MOAC   NVARCHAR2(6),
    CRS_QULC   NVARCHAR2(3),
    CRS_ESB1   NVARCHAR2(6),
    CRS_EIN1   NVARCHAR2(1),
    CRS_ESB2   NVARCHAR2(6),
    CRS_EIN2   NVARCHAR2(1),
    CRS_ESB3   NVARCHAR2(6),
    CRS_EBAL   NVARCHAR2(1),
    CRS_CTYC   NVARCHAR2(3),
    CRS_LENG   NUMBER(2),
    CRS_UOMC   NVARCHAR2(6),
    CRS_STTC   NVARCHAR2(6),
    CRS_ERFM   NVARCHAR2(1),
    CRS_XRFM   NVARCHAR2(2),
    CRS_FECM   NVARCHAR2(1),
    CRS_TTIC   NVARCHAR2(3),
    CRS_CSF1   NVARCHAR2(3),
    CRS_CSF2   NVARCHAR2(3),
    CRS_SDPTC  NVARCHAR2(12),
    CRS_CRSSTC NVARCHAR2(15),
    CRS_HEFE   NVARCHAR2(1),
    CRS_URLR   NVARCHAR2(50),
    CRS_FACC   NVARCHAR2(6),
    CRS_GSAF   VARCHAR2(1),
    CRS_GSCF   VARCHAR2(1),
    CRS_PSAC   NVARCHAR2(12),
    CRS_GAEL   NVARCHAR2(1),
    CRS_CLSC   NVARCHAR2(1),
    CRS_RESH   VARCHAR2(1),
    CRS_IUSE   VARCHAR2(1),
    CRS_FRFM   NVARCHAR2(1),
    CRS_SRFM   NVARCHAR2(1),
    CRS_ELQS   VARCHAR2(1),
    CRS_BURS   VARCHAR2(1),
    CRS_SKEO   VARCHAR2(1),
    CRS_UDF1   NVARCHAR2(15),
    CRS_UDF2   NVARCHAR2(15),
    CRS_UDF3   NVARCHAR2(15),
    CRS_UDF4   NVARCHAR2(15),
    CRS_UDF5   NVARCHAR2(15),
    CRS_UDF6   NVARCHAR2(15),
    CRS_UDF7   NVARCHAR2(15),
    CRS_UDF8   NVARCHAR2(15),
    CRS_UDF9   NVARCHAR2(15),
    CRS_UDFA   NVARCHAR2(15),
    CRS_UDFB   NVARCHAR2(15),
    CRS_UDFC   NVARCHAR2(15),
    CRS_UDFD   NVARCHAR2(15),
    CRS_UDFE   NVARCHAR2(15),
    CRS_UDFF   NVARCHAR2(15),
    CRS_UDFG   NVARCHAR2(15),
    CRS_UDFH   NVARCHAR2(15),
    CRS_UDFI   NVARCHAR2(15),
    CRS_UDFJ   NVARCHAR2(100),
    CRS_UDFK   NVARCHAR2(100),
    CRS_NOTE   NVARCHAR2(2000),
    CRS_MDOS   NUMBER(2),
    CRS_DVNC   NVARCHAR2(12),
    CRS_TAIC   NVARCHAR2(6),
    CRS_ENRC   NVARCHAR2(6),
    CRS_HASC   NVARCHAR2(12),
    CRS_ESB4   NVARCHAR2(6),
    CRS_ESB5   NVARCHAR2(6)
)
;

create index INTUIT.SRS_CRSI2
    on INTUIT.SRS_CRS (CRS_DPTC)
;

create index INTUIT.SRS_CRSI3
    on INTUIT.SRS_CRS (CRS_PRSC)
;

create index INTUIT.SRS_CRSI4
    on INTUIT.SRS_CRS (CRS_SCHC)
;

create index INTUIT.SRS_CRSI5
    on INTUIT.SRS_CRS (CRS_BEGD)
;

create index INTUIT.SRS_CRSI6
    on INTUIT.SRS_CRS (CRS_ENDD)
;

create index INTUIT.SRS_CRSI7
    on INTUIT.SRS_CRS (CRS_FPTC)
;

create index INTUIT.SRS_CRSI8
    on INTUIT.SRS_CRS (CRS_MOAC)
;

create index INTUIT.SRS_CRSI9
    on INTUIT.SRS_CRS (CRS_QULC)
;

create index INTUIT.SRS_CRSI10
    on INTUIT.SRS_CRS (CRS_ESB1)
;

create index INTUIT.SRS_CRSI11
    on INTUIT.SRS_CRS (CRS_ESB2)
;

create index INTUIT.SRS_CRSI12
    on INTUIT.SRS_CRS (CRS_CTYC)
;

create index INTUIT.SRS_CRSI13
    on INTUIT.SRS_CRS (CRS_UOMC)
;

create index INTUIT.SRS_CRSI14
    on INTUIT.SRS_CRS (CRS_STTC)
;

create index INTUIT.SRS_CRSI15
    on INTUIT.SRS_CRS (CRS_TTIC)
;

create index INTUIT.SRS_CRSI16
    on INTUIT.SRS_CRS (CRS_CSF1)
;

create index INTUIT.SRS_CRSI17
    on INTUIT.SRS_CRS (CRS_CSF2)
;

create index INTUIT.SRS_CRSI18
    on INTUIT.SRS_CRS (CRS_CGPC)
;

create table INTUIT.INS_DPT
(
    DPT_CODE NVARCHAR2(12) not null
        constraint INS_DPTP1
            primary key,
    DPT_SNAM NVARCHAR2(15),
    DPT_NAME NVARCHAR2(250),
    DPT_INSC NVARCHAR2(6),
    DPT_IUSE VARCHAR2(1),
    DPT_TYPE NVARCHAR2(12),
    DPT_FACC NVARCHAR2(6),
    DPT_UDF1 NVARCHAR2(15),
    DPT_UDF2 NVARCHAR2(15),
    DPT_UDF3 NVARCHAR2(15),
    DPT_UDF4 NVARCHAR2(15),
    DPT_UDF5 NVARCHAR2(15),
    DPT_UDF6 NVARCHAR2(15),
    DPT_UDF7 NVARCHAR2(15),
    DPT_UDF8 NVARCHAR2(15),
    DPT_UDF9 NVARCHAR2(15),
    DPT_UDFA NVARCHAR2(15),
    DPT_UDFB NVARCHAR2(15),
    DPT_UDFC NVARCHAR2(15),
    DPT_UDFD NVARCHAR2(15),
    DPT_UDFE NVARCHAR2(15),
    DPT_UDFF NVARCHAR2(15),
    DPT_UDFG NVARCHAR2(15),
    DPT_UDFH NVARCHAR2(15),
    DPT_UDFI NVARCHAR2(15),
    DPT_UDFJ NVARCHAR2(100),
    DPT_UDFK NVARCHAR2(100),
    DPT_DPT1 NVARCHAR2(12),
    DPT_CCOC NVARCHAR2(6)
)
;

create index INTUIT.INS_DPTI2
    on INTUIT.INS_DPT (DPT_INSC)
;

create table INTUIT.SRS_FAC
(
    FAC_CODE NVARCHAR2(6) not null
        constraint SRS_FACP1
            primary key,
    FAC_SNAM NVARCHAR2(15),
    FAC_NAME NVARCHAR2(100),
    FAC_IUSE VARCHAR2(1),
    FAC_UDF1 NVARCHAR2(15),
    FAC_UDF2 NVARCHAR2(15),
    FAC_UDF3 NVARCHAR2(15),
    FAC_UDF4 NVARCHAR2(15),
    FAC_UDF5 NVARCHAR2(15),
    FAC_UDF6 NVARCHAR2(15),
    FAC_UDF7 NVARCHAR2(15),
    FAC_UDF8 NVARCHAR2(15),
    FAC_UDF9 NVARCHAR2(15),
    FAC_UDFA NVARCHAR2(15),
    FAC_UDFB NVARCHAR2(15),
    FAC_UDFC NVARCHAR2(15),
    FAC_UDFD NVARCHAR2(15),
    FAC_UDFE NVARCHAR2(15),
    FAC_UDFF NVARCHAR2(15),
    FAC_UDFG NVARCHAR2(15),
    FAC_UDFH NVARCHAR2(15),
    FAC_UDFI NVARCHAR2(15),
    FAC_UDFJ NVARCHAR2(100),
    FAC_UDFK NVARCHAR2(100)
)
;

create table INTUIT.CAM_LEV
(
    LEV_CODE NVARCHAR2(6) not null
        constraint CAM_LEVP1
            primary key,
    LEV_SNAM NVARCHAR2(15),
    LEV_NAME NVARCHAR2(50),
    LEV_IUSE VARCHAR2(1)
)
;
create table INTUIT.INS_LCA
(
    LCA_CODE NVARCHAR2(12) not null
        constraint INS_LCAP1
            primary key,
    LCA_SNAM NVARCHAR2(15),
    LCA_NAME NVARCHAR2(50),
    LCA_CMPC NVARCHAR2(1),
    LCA_SITC NVARCHAR2(12),
    LCA_IUSE VARCHAR2(1),
    LCA_LAD1 NVARCHAR2(50),
    LCA_LAD2 NVARCHAR2(50),
    LCA_LAD3 NVARCHAR2(50),
    LCA_LAD4 NVARCHAR2(50),
    LCA_LAD5 NVARCHAR2(50),
    LCA_LAPC NVARCHAR2(12),
    LCA_UDF1 NVARCHAR2(15),
    LCA_UDF2 NVARCHAR2(15),
    LCA_UDF3 NVARCHAR2(15),
    LCA_UDF4 NVARCHAR2(15),
    LCA_UDF5 NVARCHAR2(15),
    LCA_UDF6 NVARCHAR2(15),
    LCA_UDF7 NVARCHAR2(15),
    LCA_UDF8 NVARCHAR2(15),
    LCA_UDF9 NVARCHAR2(15),
    LCA_UDFA NVARCHAR2(15),
    LCA_UDFB NVARCHAR2(15),
    LCA_UDFC NVARCHAR2(15),
    LCA_UDFD NVARCHAR2(15),
    LCA_UDFE NVARCHAR2(15),
    LCA_UDFF NVARCHAR2(15),
    LCA_UDFG NVARCHAR2(15),
    LCA_UDFH NVARCHAR2(15),
    LCA_UDFI NVARCHAR2(15),
    LCA_UDFJ NVARCHAR2(100),
    LCA_UDFK NVARCHAR2(100),
    LCA_STOK VARCHAR2(1),
    LCA_CNTY NVARCHAR2(50),
    LCA_MSRT NVARCHAR2(25),
    LCA_EMAD NVARCHAR2(100),
    LCA_TELN NVARCHAR2(20),
    LCA_HLCC NVARCHAR2(12),
    LCA_LCID NVARCHAR2(15)
)
;

create index INTUIT.INS_LCAI2
    on INTUIT.INS_LCA (LCA_CMPC)
;


create table INTUIT.CAM_MDS
(
    MOD_CODE NVARCHAR2(12) not null,
    MDS_SEQN NVARCHAR2(4)  not null,
    MDS_DVNC NVARCHAR2(12),
    MDS_AYRC NVARCHAR2(12),
    MDS_TITL NVARCHAR2(120),
    MDS_UDF1 NVARCHAR2(15),
    MDS_UDF2 NVARCHAR2(15),
    MDS_UDF3 NVARCHAR2(15),
    MDS_UDF4 NVARCHAR2(15),
    MDS_UDF5 NVARCHAR2(15),
    MDS_UDF6 NVARCHAR2(15),
    MDS_UDF7 NVARCHAR2(15),
    MDS_UDF8 NVARCHAR2(15),
    MDS_UDF9 NVARCHAR2(15),
    MDS_UDFA NVARCHAR2(15),
    MDS_UDFB NVARCHAR2(15),
    MDS_UDFC NVARCHAR2(15),
    MDS_UDFD NVARCHAR2(15),
    MDS_UDFE NVARCHAR2(15),
    MDS_UDFF NVARCHAR2(15),
    MDS_UDFG NVARCHAR2(15),
    MDS_UDFH NVARCHAR2(15),
    MDS_UDFI NVARCHAR2(15),
    MDS_UDFJ NVARCHAR2(100),
    MDS_UDFK NVARCHAR2(100),
    MOD_DESC NCLOB,
    MDS_DESV NCLOB,
    constraint CAM_MDSP1
        primary key (MOD_CODE, MDS_SEQN)
)
;

create index INTUIT.CAM_MDSI2
    on INTUIT.CAM_MDS (MOD_CODE)
;

create table INTUIT.CAM_MAV
(
    MOD_CODE  NVARCHAR2(12) not null,
    MAV_OCCUR NVARCHAR2(6)  not null,
    AYR_CODE  NVARCHAR2(12) not null,
    PSL_CODE  NVARCHAR2(6)  not null,
    SCH_CODE  NVARCHAR2(6),
    LEV_CODE  NVARCHAR2(6),
    SHS_CODE  NVARCHAR2(6),
    LCA_CODE  NVARCHAR2(12),
    MAV_TRGT  NUMBER(4),
    MAV_ACTL  NUMBER(4),
    MAV_ACTS  NUMBER(4),
    MAV_ACTM  NUMBER(4),
    MAV_CHIN  NUMBER(4),
    MAV_COUT  NUMBER(4),
    MAV_BEGP  NVARCHAR2(1),
    MAV_ENDP  NVARCHAR2(1),
    DAY_CODE  NVARCHAR2(1),
    MAV_STIME DATE,
    MAP_CODE  NVARCHAR2(12),
    MKS_CODE  NVARCHAR2(6),
    MAV_PSEQ  NUMBER(2),
    MAV_WPER  NUMBER(4, 1),
    MAV_GLHR  NUMBER(5),
    MAV_MACC  NVARCHAR2(6),
    DOM_CODE  NVARCHAR2(12),
    PRS_CODE  NVARCHAR2(12),
    MAV_BEGW  NUMBER(2),
    MAV_ENDW  NUMBER(2),
    MAV_TELT  CHAR,
    DPT_CODE  NVARCHAR2(12),
    MAV_DISPA NVARCHAR2(1),
    MAV_TOCC  NVARCHAR2(12),
    MAV_VLYN  VARCHAR2(1),
    MAV_PER1  NUMBER(4),
    MAV_PER2  NUMBER(4),
    MAV_ARNN  NUMBER(6),
    MAV_UDF1  NVARCHAR2(15),
    MAV_UDF2  NVARCHAR2(15),
    MAV_UDF3  NVARCHAR2(15),
    MAV_UDF4  NVARCHAR2(15),
    MAV_UDF5  NVARCHAR2(15),
    MAV_UDF6  NVARCHAR2(15),
    MAV_UDF7  NVARCHAR2(15),
    MAV_UDF8  NVARCHAR2(15),
    MAV_UDF9  NVARCHAR2(15),
    MAV_UDFA  NVARCHAR2(15),
    MAV_UDFB  NVARCHAR2(15),
    MAV_UDFC  NVARCHAR2(15),
    MAV_UDFD  NVARCHAR2(15),
    MAV_UDFE  NVARCHAR2(15),
    MAV_UDFF  NVARCHAR2(15),
    MAV_UDFG  NVARCHAR2(15),
    MAV_UDFH  NVARCHAR2(15),
    MAV_UDFI  NVARCHAR2(15),
    MAV_UDFJ  NVARCHAR2(100),
    MAV_UDFK  NVARCHAR2(100),
    MAV_REGM  NVARCHAR2(1),
    MAV_MAVN  NVARCHAR2(120),
    MAV_HLCC  NVARCHAR2(12),
    MAV_EXMR  NVARCHAR2(1),
    MAV_FRID  VARCHAR2(1),
    MAV_TIII  NVARCHAR2(12),
    MAV_WAIT  VARCHAR2(1),
    MAV_ACTW  NUMBER(4),
    MAV_MAVC  NUMBER(5, 2),
    MAV_ADPC  NVARCHAR2(12),
    constraint CAM_MAVP1
        primary key (MOD_CODE, MAV_OCCUR, AYR_CODE, PSL_CODE)
)
;

create index INTUIT.CAM_MAVI2
    on INTUIT.CAM_MAV (MOD_CODE)
;

create index INTUIT.CAM_MAVI3
    on INTUIT.CAM_MAV (AYR_CODE, PSL_CODE)
;

create index INTUIT.CAM_MAVI4
    on INTUIT.CAM_MAV (SCH_CODE, LEV_CODE)
;

create index INTUIT.CAM_MAVI5
    on INTUIT.CAM_MAV (MAP_CODE)
;

create index INTUIT.CAM_MAVI6
    on INTUIT.CAM_MAV (MOD_CODE, AYR_CODE, PSL_CODE)
;

create index INTUIT.CAM_MAVI7
    on INTUIT.CAM_MAV (PSL_CODE)
;

create table INTUIT.CAM_TOP
(
    TOP_CODE NVARCHAR2(12) not null
        constraint CAM_TOPP1
            primary key,
    TOP_SNAM NVARCHAR2(15),
    TOP_NAME NVARCHAR2(50),
    TOP_PERC NUMBER(3),
    MOD_CODE NVARCHAR2(12),
    SUB_CODE NVARCHAR2(12),
    DPT_CODE NVARCHAR2(12),
    TOP_IUSE VARCHAR2(1),
    TOP_UDF1 NVARCHAR2(15),
    TOP_UDF2 NVARCHAR2(15),
    TOP_UDF3 NVARCHAR2(15),
    TOP_UDF4 NVARCHAR2(15),
    TOP_UDF5 NVARCHAR2(15),
    TOP_UDF6 NVARCHAR2(15),
    TOP_UDF7 NVARCHAR2(15),
    TOP_UDF8 NVARCHAR2(15),
    TOP_UDF9 NVARCHAR2(15),
    TOP_UDFA NVARCHAR2(15),
    TOP_UDFB NVARCHAR2(15),
    TOP_UDFC NVARCHAR2(15),
    TOP_UDFD NVARCHAR2(15),
    TOP_UDFE NVARCHAR2(15),
    TOP_UDFF NVARCHAR2(15),
    TOP_UDFG NVARCHAR2(15),
    TOP_UDFH NVARCHAR2(15),
    TOP_UDFI NVARCHAR2(15),
    TOP_UDFJ NVARCHAR2(100),
    TOP_UDFK NVARCHAR2(100)
)
;

create index INTUIT.CAM_TOPI2
    on INTUIT.CAM_TOP (MOD_CODE)
;

create index INTUIT.CAM_TOPI3
    on INTUIT.CAM_TOP (DPT_CODE)
;

create index INTUIT.CAM_TOPI4
    on INTUIT.CAM_TOP (SUB_CODE)
;

